In [1]:
import pandas as pd
import numpy as np
import math
import os
import warnings
print('Modulos importados')

Modulos importados

In [1]:
text_1 = 'AABBB ABBAB ABABA AAAAA ABBBA BAAAA ABAAA ABBAA AAABA ABAAA ABBBA AABAA AAABB AABAA ABABA AAAAA AAABA ABBAB ABABA ABAAA ABBAA AAAAA AAAAA AAABA AAAAA BAAAB ABBAB AABAA BAAAB BAABA ABBAB AAABA BAABB AABAA ABBAA BAABA AAAAA AAABA ABBAB ABABB ABBAB ABBAB BAABA BAAAA AAAAA AAABA AAAAA BAAAA BAABA AAAAA ABBAA ABBAB AABAA BAAAB BAABA ABBAB BABBA BAAAB AABAA AABBA BAABB BAAAA ABBAB ABBBB BAABB ABAAA AABAA BAAAA ABBAB ABBBA AABAA ABBAA BAAAB AAAAA BAAAA ABBBB BAABB AABAA ABBAA ABBAB ABBBA ABBAB BAAAA ABBBB BAABB AABAA ABABB ABAAA AABAA ABBAA BAABA BAAAA AAAAA BAAAB ABABA AAAAA ABBBA BAAAA ABAAA ABABB AABAA BAAAA AAAAA ABABA AAAAA ABBAB AAAAB BAABA BAABB BAABB ABAAA BAAAB BAABA AABAA AAABA ABBAB ABBAA BAABA ABBAB AAABB ABBAB AABAA ABABA AABAA BAAAB AABAB BAABB AABAA BAAAA BABBB ABBAB AAABB AABAA BAABA AABAA ABBAA AABAA BAAAA ABBBB BAABB AABAA AAABB AABAA BAAAB AAABB ABBAB AAAAB ABABA AAAAA BAAAA BAABB ABBAA ABBBA AABAA AAABB AAAAA BABBB ABBAB AAABB AABAA ABBBA AAAAA ABBBA AABAA ABABA BAAAB ABAAA AABAA BAAAB BAABA AAAAA BAAAB ABABA AABAA BABBA AABAA ABBAA AAABB ABBAB AABAA BAAAB BAABA ABBAB BAAAB ABAAA AABBA ABBAA ABAAA AABAB ABAAA AAABA AAAAA AAABB AABAA BAABB AABAA BAAAA AAABB AAAAA AAABB BAABA ABAAA AABAA ABBAA AABAA BAAAB BAABA AAAAA ABABA AABAA ABBAA BAABA ABBAB ABBBA AAAAA BAAAA AAAAA BAAAA AABAA BAAAB ABBAB ABABA BAABB AABAA BAAAA BAABB ABBAA AAAAA AAABA AABAA BAAAA BAABA ABAAA ABAAA ABBAB BABBA AAAAA BAAAB AABAA BABBA AAAAA BAAAB AABAA ABBAA ABBAB AABAB BAABB AABAA ABABB BAABB BABBA AAABB ABAAA AABAB ABAAA AAABA ABAAA ABABA ABBBA AABAA BAAAA ABBAB ABBAA BAABB ABBAA AAABA AAAAA ABABA ABBAB AABAA BAAAB AAABA BAABB AAAAA ABBAA AAABB ABBAB ABBAA ABBAB AABAA BAAAB BAABA AAAAA BAAAB AAAAB BAABB BAAAB AAABA AAAAA ABBAA AAABB ABBAB BAAAA AABAA BAAAB ABBAB ABABA BAABB AABAA BAAAA BAABB ABBAA ABBAB AABAA ABBAA AAABA AAAAA ABABB AAAAB ABAAA ABBAB AAABA BAABB AAAAA ABBAA AAABB ABBAB BAABA ABAAA AABAA ABBAA AABAA BAAAB ABABA AAAAA ABABB AABAA ABBAA BAABA AABAA AABAA ABBAA ABABA ABBAB BAAAB AAAAA AAABA AABAA BAAAA BAABA ABAAA ABAAA ABBAB BAAAB ABBAB AABBB BAABA ABBAB AAABB ABBAB ABBBA BAABB AABAA AAABB AABAA ABBBA AAAAA BAAAB AAAAA BAAAA ABBAA ABBAB AAABA BAAAA AABAA AABAA BAAAB AABAA BAAAB ABBBA AABAA BAAAA ABBAB ABABA ABBAB AABAA BAAAB BAABA AABAA BAAAB AAABB ABAAA BAAAB AABAB BAAAA BAABB BAABA AAAAA ABBAA AAABB ABBAB ABBAA BAABB ABBAA AAABA AAAAA AAABB BAABB AAABB AABAA AAABB AABAA ABBBB BAABB AABAA ABBBA ABBAB AAABB BAAAA ABAAA AAAAA BAAAB BAAAB ABBAB AAAAB BAAAA AABAA BAABA ABBAB AAABB ABBAB AABAA ABABA AAABB ABAAA AAAAA AAABB AABAA BAAAB ABBBA BAABB AABAA BAAAB AAABB AABAA ABBAA AAAAA BAABB ABAAA AAABB AAAAA AAABB ABBAB AABBB ABABB ABAAA ABBBB BAABB AABAA BAAAA ABAAA AAABB ABBAB BAABB ABAAA BAABB AAAAA ABABA AAABB ABAAA ABBAA ABBAB BAABA ABAAA AABAA ABBAA AABAA BAAAB ABAAA AAABB AABAA AAAAA ABABA ABBAB ABABB BAABB AAABA AABBB ABBAB ABBBB BAABB AABAA ABABB AABAA AABBA BAABB BAAAB BAABA AAAAA BAAAB AAABB ABAAA ABABB AABAA ABABA AAAAA ABAAA ABBAA BAABA AABAA ABBAA AAABA ABAAA ABBAB ABBAA ABBBB BAABB AABAA BAAAB ABAAA AABAA ABBAA BAABA ABBAB ABBBA ABBAB BAAAA BAABA ABAAA AABAA BAAAB BAABA AAAAA BAAAB ABAAA AABAA ABBAA AAABB ABBAB ABBAB AAAAB BAABB ABAAA AAAAA BABBA BAAAB BAABB AABAB ABAAA AAABA ABAAA AABAA ABBAA BAABA AABAA'

In [2]:
text_2 = 'AABBB ABBAB ABABA AAAAA ABBBA BAAAA ABAAA ABBAA AAABA ABAAA ABBBA AABAA AAABB AABAA ABABA AAAAA AAABA ABBAB ABABA ABAAA ABBAA AAAAA AAAAA AAABA AAAAA BAAAB ABBAB AABAA BAAAB BAABA ABBAB AAABA BAABB AABAA ABBAA BAABA AAAAA AAABA ABBAB ABABB ABBAB ABBAB BAABA BAAAA AAAAA AAABA AAAAA BAAAA BAABA AAAAA ABBAA ABBAB AABAA BAAAB BAABA ABBAB BABBA BAAAB AABAA AABBA BAABB BAAAA ABBAB ABBBB BAABB ABAAA AABAA BAAAA ABBAB ABBBA AABAA ABBAA BAAAB AAAAA BAAAA ABBBB BAABB AABAA ABBAA ABBAB ABBBA ABBAB BAAAA ABBBB BAABB AABAA ABABB ABAAA AABAA ABBAA BAABA BAAAA AAAAA BAAAB ABABA AAAAA ABBBA BAAAA ABAAA ABABB AABAA BAAAA AAAAA ABABA AAAAA ABBAB AAAAB BAABA BAABB BAABB ABAAA BAAAB BAABA AABAA AAABA ABBAB ABBAA BAABA ABBAB AAABB ABBAB AABAA ABABA AABAA BAAAB AABAB BAABB AABAA BAAAA BABBB ABBAB AAABB AABAA BAABA AABAA ABBAA AABAA BAAAA ABBBB BAABB AABAA AAABB AABAA BAAAB AAABB ABBAB AAAAB ABABA AAAAA BAAAA BAABB ABBAA ABBBA AABAA AAABB AAAAA BABBB ABBAB AAABB AABAA ABBBA AAAAA ABBBA AABAA ABABA BAAAB ABAAA AABAA BAAAB BAABA AAAAA BAAAB ABABA AABAA BABBA AABAA ABBAA AAABB ABBAB AABAA BAAAB BAABA ABBAB BAAAB ABAAA AABBA ABBAA ABAAA AABAB ABAAA AAABA AAAAA AAABB AABAA BAABB AABAA BAAAA AAABB AAAAA AAABB BAABA ABAAA AABAA ABBAA AABAA BAAAB BAABA AAAAA ABABA AABAA ABBAA BAABA ABBAB ABBBA AAAAA BAAAA AAAAA BAAAA AABAA BAAAB ABBAB ABABA BAABB AABAA BAAAA BAABB ABBAA AAAAA AAABA AABAA BAAAA BAABA ABAAA ABAAA ABBAB BABBA AAAAA BAAAB AABAA BABBA AAAAA BAAAB AABAA ABBAA ABBAB AABAB BAABB AABAA ABABB BAABB BABBA AAABB ABAAA AABAB ABAAA AAABA ABAAA ABABA ABBBA AABAA BAAAA ABBAB ABBAA BAABB ABBAA AAABA AAAAA ABABA ABBAB AABAA BAAAB AAABA BAABB AAAAA ABBAA AAABB ABBAB ABBAA ABBAB AABAA BAAAB BAABA AAAAA BAAAB AAAAB BAABB BAAAB AAABA AAAAA ABBAA AAABB ABBAB BAAAA AABAA BAAAB ABBAB ABABA BAABB AABAA BAAAA BAABB ABBAA ABBAB AABAA ABBAA AAABA AAAAA ABABB AAAAB ABAAA ABBAB AAABA BAABB AAAAA ABBAA AAABB ABBAB BAABA ABAAA AABAA ABBAA AABAA BAAAB ABABA AAAAA ABABB AABAA ABBAA BAABA AABAA AABAA ABBAA ABABA ABBAB BAAAB AAAAA AAABA AABAA BAAAA BAABA ABAAA ABAAA ABBAB BAAAB ABBAB AABBB BAABA ABBAB AAABB ABBAB ABBBA BAABB AABAA AAABB AABAA ABBBA AAAAA BAAAB AAAAA BAAAA ABBAA ABBAB AAABA BAAAA AABAA AABAA BAAAB AABAA BAAAB ABBBA AABAA BAAAA ABBAB ABABA ABBAB AABAA BAAAB BAABA AABAA BAAAB AAABB ABAAA BAAAB AABAB BAAAA BAABB BAABA AAAAA ABBAA AAABB ABBAB ABBAA BAABB ABBAA AAABA AAAAA AAABB BAABB AAABB AABAA AAABB AABAA ABBBB BAABB AABAA ABBBA ABBAB AAABB BAAAA ABAAA AAAAA BAAAB BAAAB ABBAB AAAAB BAAAA AABAA BAABA ABBAB AAABB ABBAB AABAA ABABA AAABB ABAAA AAAAA AAABB AABAA BAAAB ABBBA BAABB AABAA BAAAB AAABB AABAA ABBAA AAAAA BAABB ABAAA AAABB AAAAA AAABB ABBAB AABBB ABABB ABAAA ABBBB BAABB AABAA BAAAA ABAAA AAABB ABBAB BAABB ABAAA BAABB AAAAA ABABA AAABB ABAAA ABBAA ABBAB BAABA ABAAA AABAA ABBAA AABAA BAAAB ABAAA AAABB AABAA AAAAA ABABA ABBAB ABABB BAABB AAABA AABBB ABBAB ABBBB BAABB AABAA ABABB AABAA AABBA BAABB BAAAB BAABA AAAAA BAAAB AAABB ABAAA ABABB AABAA ABABA AAAAA ABAAA ABBAA BAABA AABAA ABBAA AAABA ABAAA ABBAB ABBAA ABBBB BAABB AABAA BAAAB ABAAA AABAA ABBAA BAABA ABBAB ABBBA ABBAB BAAAA BAABA ABAAA AABAA BAAAB BAABA AAAAA BAAAB ABAAA AABAA ABBAA AAABB ABBAB ABBAB AAAAB BAABB ABAAA AAAAA BABBA BAAAB BAABB AABAB ABAAA AAABA ABAAA AABAA ABBAA BAABA AABAA'

In [8]:
text_1 = text_1.replace("A","1")
text_1 = text_1.replace("B","0")
print(text_1)

11000 10010 10101 11111 10001 01111 10111 10011 11101 10111 10001 11011 11100 11011 10101 11111 11101 10010 10101 10111 10011 11111 11111 11101 11111 01110 10010 11011 01110 01101 10010 11101 01100 11011 10011 01101 11111 11101 10010 10100 10010 10010 01101 01111 11111 11101 11111 01111 01101 11111 10011 10010 11011 01110 01101 10010 01001 01110 11011 11001 01100 01111 10010 10000 01100 10111 11011 01111 10010 10001 11011 10011 01110 11111 01111 10000 01100 11011 10011 10010 10001 10010 01111 10000 01100 11011 10100 10111 11011 10011 01101 01111 11111 01110 10101 11111 10001 01111 10111 10100 11011 01111 11111 10101 11111 10010 11110 01101 01100 01100 10111 01110 01101 11011 11101 10010 10011 01101 10010 11100 10010 11011 10101 11011 01110 11010 01100 11011 01111 01000 10010 11100 11011 01101 11011 10011 11011 01111 10000 01100 11011 11100 11011 01110 11100 10010 11110 10101 11111 01111 01100 10011 10001 11011 11100 11111 01000 10010 11100 11011 10001 11111 10001 11011 10101 01110 10111 11011 01110 01101 11111 01110 10101 11011 01001 11011 10011 11100 10010 11011 01110 01101 10010 01110 10111 11001 10011 10111 11010 10111 11101 11111 11100 11011 01100 11011 01111 11100 11111 11100 01101 10111 11011 10011 11011 01110 01101 11111 10101 11011 10011 01101 10010 10001 11111 01111 11111 01111 11011 01110 10010 10101 01100 11011 01111 01100 10011 11111 11101 11011 01111 01101 10111 10111 10010 01001 11111 01110 11011 01001 11111 01110 11011 10011 10010 11010 01100 11011 10100 01100 01001 11100 10111 11010 10111 11101 10111 10101 10001 11011 01111 10010 10011 01100 10011 11101 11111 10101 10010 11011 01110 11101 01100 11111 10011 11100 10010 10011 10010 11011 01110 01101 11111 01110 11110 01100 01110 11101 11111 10011 11100 10010 01111 11011 01110 10010 10101 01100 11011 01111 01100 10011 10010 11011 10011 11101 11111 10100 11110 10111 10010 11101 01100 11111 10011 11100 10010 01101 10111 11011 10011 11011 01110 10101 11111 10100 11011 10011 01101 11011 11011 10011 10101 10010 01110 11111 11101 11011 01111 01101 10111 10111 10010 01110 10010 11000 01101 10010 11100 10010 10001 01100 11011 11100 11011 10001 11111 01110 11111 01111 10011 10010 11101 01111 11011 11011 01110 11011 01110 10001 11011 01111 10010 10101 10010 11011 01110 01101 11011 01110 11100 10111 01110 11010 01111 01100 01101 11111 10011 11100 10010 10011 01100 10011 11101 11111 11100 01100 11100 11011 11100 11011 10000 01100 11011 10001 10010 11100 01111 10111 11111 01110 01110 10010 11110 01111 11011 01101 10010 11100 10010 11011 10101 11100 10111 11111 11100 11011 01110 10001 01100 11011 01110 11100 11011 10011 11111 01100 10111 11100 11111 11100 10010 11000 10100 10111 10000 01100 11011 01111 10111 11100 10010 01100 10111 01100 11111 10101 11100 10111 10011 10010 01101 10111 11011 10011 11011 01110 10111 11100 11011 11111 10101 10010 10100 01100 11101 11000 10010 10000 01100 11011 10100 11011 11001 01100 01110 01101 11111 01110 11100 10111 10100 11011 10101 11111 10111 10011 01101 11011 10011 11101 10111 10010 10011 10000 01100 11011 01110 10111 11011 10011 01101 10010 10001 10010 01111 01101 10111 11011 01110 01101 11111 01110 10111 11011 10011 11100 10010 10010 11110 01100 10111 11111 01001 01110 01100 11010 10111 11101 10111 11011 10011 01101 11011

In [9]:
text_2 = text_2.replace("A","0")
text_2 = text_2.replace("B","1")
print(text_2)

00111 01101 01010 00000 01110 10000 01000 01100 00010 01000 01110 00100 00011 00100 01010 00000 00010 01101 01010 01000 01100 00000 00000 00010 00000 10001 01101 00100 10001 10010 01101 00010 10011 00100 01100 10010 00000 00010 01101 01011 01101 01101 10010 10000 00000 00010 00000 10000 10010 00000 01100 01101 00100 10001 10010 01101 10110 10001 00100 00110 10011 10000 01101 01111 10011 01000 00100 10000 01101 01110 00100 01100 10001 00000 10000 01111 10011 00100 01100 01101 01110 01101 10000 01111 10011 00100 01011 01000 00100 01100 10010 10000 00000 10001 01010 00000 01110 10000 01000 01011 00100 10000 00000 01010 00000 01101 00001 10010 10011 10011 01000 10001 10010 00100 00010 01101 01100 10010 01101 00011 01101 00100 01010 00100 10001 00101 10011 00100 10000 10111 01101 00011 00100 10010 00100 01100 00100 10000 01111 10011 00100 00011 00100 10001 00011 01101 00001 01010 00000 10000 10011 01100 01110 00100 00011 00000 10111 01101 00011 00100 01110 00000 01110 00100 01010 10001 01000 00100 10001 10010 00000 10001 01010 00100 10110 00100 01100 00011 01101 00100 10001 10010 01101 10001 01000 00110 01100 01000 00101 01000 00010 00000 00011 00100 10011 00100 10000 00011 00000 00011 10010 01000 00100 01100 00100 10001 10010 00000 01010 00100 01100 10010 01101 01110 00000 10000 00000 10000 00100 10001 01101 01010 10011 00100 10000 10011 01100 00000 00010 00100 10000 10010 01000 01000 01101 10110 00000 10001 00100 10110 00000 10001 00100 01100 01101 00101 10011 00100 01011 10011 10110 00011 01000 00101 01000 00010 01000 01010 01110 00100 10000 01101 01100 10011 01100 00010 00000 01010 01101 00100 10001 00010 10011 00000 01100 00011 01101 01100 01101 00100 10001 10010 00000 10001 00001 10011 10001 00010 00000 01100 00011 01101 10000 00100 10001 01101 01010 10011 00100 10000 10011 01100 01101 00100 01100 00010 00000 01011 00001 01000 01101 00010 10011 00000 01100 00011 01101 10010 01000 00100 01100 00100 10001 01010 00000 01011 00100 01100 10010 00100 00100 01100 01010 01101 10001 00000 00010 00100 10000 10010 01000 01000 01101 10001 01101 00111 10010 01101 00011 01101 01110 10011 00100 00011 00100 01110 00000 10001 00000 10000 01100 01101 00010 10000 00100 00100 10001 00100 10001 01110 00100 10000 01101 01010 01101 00100 10001 10010 00100 10001 00011 01000 10001 00101 10000 10011 10010 00000 01100 00011 01101 01100 10011 01100 00010 00000 00011 10011 00011 00100 00011 00100 01111 10011 00100 01110 01101 00011 10000 01000 00000 10001 10001 01101 00001 10000 00100 10010 01101 00011 01101 00100 01010 00011 01000 00000 00011 00100 10001 01110 10011 00100 10001 00011 00100 01100 00000 10011 01000 00011 00000 00011 01101 00111 01011 01000 01111 10011 00100 10000 01000 00011 01101 10011 01000 10011 00000 01010 00011 01000 01100 01101 10010 01000 00100 01100 00100 10001 01000 00011 00100 00000 01010 01101 01011 10011 00010 00111 01101 01111 10011 00100 01011 00100 00110 10011 10001 10010 00000 10001 00011 01000 01011 00100 01010 00000 01000 01100 10010 00100 01100 00010 01000 01101 01100 01111 10011 00100 10001 01000 00100 01100 10010 01101 01110 01101 10000 10010 01000 00100 10001 10010 00000 10001 01000 00100 01100 00011 01101 01101 00001 10011 01000 00000 10110 10001 10011 00101 01000 00010 01000 00100 01100 10010 00100

In [10]:
text_2.decode(encoding='utf-8', errors='strict')

AttributeError: 'str' object has no attribute 'decode'

In [5]:
# data
Student = {
    'Name': ['John', 'Jay', 'sachin', 'Geetha', 'Amutha', 'ganesh'],
    'gender': ['male', 'male', 'male', 'female', 'female', 'male'],
    'math score': [50, 100, 70, 80, 75, 40],
    'test preparation': ['none', 'completed', 'none', 'completed',
                         'completed', 'none'],
}
  
# creating a Dataframe object
df = pd.DataFrame(Student)

In [6]:
df

     Name  gender  math score test preparation
0    John    male          50             none
1     Jay    male         100        completed
2  sachin    male          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh    male          40             none

In [7]:
# Applying the condition
df.loc[df["gender"] == "male", "gender"] = 1

In [8]:
df

     Name  gender  math score test preparation
0    John       1          50             none
1     Jay       1         100        completed
2  sachin       1          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh       1          40             none