# Yearly average players dataframes

En este script nos dedicaremos a crear una base de datos limpia segmentada por hitters y fielders. Se divide en las siguientes secciones:

- **Visualización del contenido de las bases de datos.**
- **Limpieza de la base de datos y exportación.**
- **Construcción de variables para estimaciones.**
- **Unión de las bases de datos para nuevas bases transversales.**
- **Segmentación de bases datos de acuerdo a la agencia libre.**
- **Realización del panel data de acuerdo a las especificaciones.**
- **Generación de las variables para el modelo dinámico.**

Importemos los modulos necesarios así como especificar la configuración deseada.

In [17]:
import pandas as pd
import numpy as np
import math
import os
import warnings
import statsmodels.api as sm
from matplotlib.colors import ListedColormap
from termcolor import colored
print('Modulos importados')

Modulos importados

In [18]:
# Configuraciones
warnings.filterwarnings('ignore')

In [19]:
# Directorio de trabajo
print("Directorio de trabajo previo: " + str(os.getcwd()))
# Cambiemoslo
os.chdir('/home/usuario/Documentos/Github/Proyectos/MLB_HN/')

Directorio de trabajo previo: /home/usuario/Documentos/Github/Proyectos/MLB_HN

In [20]:
# Veamos el directorio actual de trabajo
print(os.getcwd())
# El directorio anterior es el correcto, pero si no lo fuese, hacemos lo sigueinte:
path = '/home/usuario/Documentos/Github/Proyectos/MLB_HN'
print("Nuevo directorio de trabajo: " + str(os.chdir(path)))

/home/usuario/Documentos/Github/Proyectos/MLB_HN
Nuevo directorio de trabajo: None

## Visualización de las bases de datos

### Equipos por estado

In [21]:
states = 'Data/Teams/team_states.csv'
df_states = pd.read_csv(states)

In [22]:
df_states.head()

       Estado  Cantidad de equipos
0     Alabama                    0
1      Alaska                    0
2     Arizona                    1
3    Arkansas                    0
4  California                    5

### Acrónimos

Nos servirá como llave intermedia para unificar las bases de datos de los equipos

In [23]:
acronym = 'Data/Teams/team_acronym.csv'
df_acronym = pd.read_csv(acronym)

In [24]:
df_acronym.head()

                 Equipo Acronimo         Estado
0  Arizona Diamondbacks      ARI        Arizona
1        Atlanta Braves      ATL        Georgia
2     Baltimore Orioles      BAL       Maryland
3        Boston Red Sox      BOS  Massachusetts
4          Chicago Cubs      CHC       Illinois

Unamos esta dataframe con el de los equipos por estado

In [25]:
acronym_state = pd.merge(df_states, df_acronym, on = 'Estado')

In [26]:
acronym_state.head()

       Estado  Cantidad de equipos                Equipo Acronimo
0     Arizona                    1  Arizona Diamondbacks      ARI
1  California                    5    Los Angeles Angels      LAA
2  California                    5   Los Angeles Dodgers      LAD
3  California                    5     Oakland Athletics      OAK
4  California                    5      San Diego Padres       SD

En este caso, el nombre de las variables es claro

## Algoritmo para la creación de las bases de datos

A continuaicón, se optimizará el código para que se puedan obtener los *dataframes* anteriores para un cojuntos de datos de años secuenciales, como es nuestro caso

In [27]:
# Auxiliares:
free_agents = 'Data/Free_Agents/free_agents_'
hitting = 'Data/Statistics/Yearly_Average/Hitting/hitting_'
pitching = 'Data/Statistics/Yearly_Average/Pitching/pitching_'
salary = 'Data/Salary/salary_'
teams = 'ETL_Data/Transversal/Teams/free_agents_team_'
csv = '.csv'
period = 12
# Originales:
df_free_agents = [None]*period
df_hitting = [None]*period
df_pitching = [None]*period
df_salary = [None]*period
df_teams = [None]*period
# Copias:
df_free_agents_copy = [None]*period
df_hitting_copy = [None]*period
df_pitching_copy = [None]*period
df_salary_copy = [None]*period
df_teams_copy = [None]*period
# Producto final:
df_pitchers = [None]*period
df_hitters = [None]*period
df_pitchers_free_agents = [None]*period
df_hitters_free_agents = [None]*period
df_pitchers_no_free_agents = [None]*period
df_hitters_no_free_agents = [None]*period
df_panel_hitters = [None]*period
df_panel_pitchers = [None]*period

Leamos todos los archivos y creemos las copias

In [28]:
for year in range(0,period):    
    df_free_agents[year] = pd.read_csv(free_agents + str(2011 + year) + csv)
    df_hitting[year] = pd.read_csv(hitting + str(2011 + year) + csv)
    df_pitching[year] = pd.read_csv(pitching + str(2011 + year) + csv)
    df_salary[year] = pd.read_csv(salary + str(2011 + year) + csv)
    df_teams[year] = pd.read_csv(teams + str(2011 + year) + csv)
    
    df_free_agents_copy[year] = df_free_agents[year].copy()
    df_hitting_copy[year] = df_hitting[year].copy()
    df_pitching_copy[year] = df_pitching[year].copy()
    df_salary_copy[year] = df_salary[year].copy()
    df_teams_copy[year] = pd.read_csv(teams + str(2011 + year) + csv)

Tratemos las bases de datos por separado. Sin embargo, a todas les quitaremos la columna de rango y *Cash2023*.

Como no queremos que se repita la columna del año de la temporada de la base de datos, borremos la columna de *Year* de la base  de datos de los agentes libres. Como los años del contrato aparecen en la base de datos sobre los salarios, se prefiere conservar dicha columna en la base de datos de salarios puesto que esta base de datos es más general que la de los agentes libres, razón por la que se borrará de esta última base de datos. 

El equipo al que se cambia el agente libre está señalado por la columna del equipo en la base de datos de salarios y la estadísticas deportivas por lo que se borrará *Team From To* de la base de datos de los agentes libres. 

Como nos importan los salarios para este analisis, quitaremos la columna de los equipos en las bases de datos sobre las estadísticas deportivas de todos los jugadores, así como la posición que ocupan.

In [29]:
for year in range(0,period):
    # Drop columns:
    if any(name in df_free_agents_copy[year].columns for name in ['Rank','Pos','Year','Team From To']):
        df_free_agents_copy[year].drop('Rank', axis = 1, inplace = True)
        df_free_agents_copy[year].drop('Year', axis = 1, inplace = True)
        df_free_agents_copy[year].drop('Pos', axis = 1, inplace = True)
        df_free_agents_copy[year].drop('Team From To', axis = 1, inplace = True)
    if 'Rank' in df_salary_copy[year].columns:
        df_salary_copy[year].drop('Rank', axis = 1, inplace = True)
    if any(name in df_hitting_copy[year].columns for name in ['Rank','Year','Cash2023','Team','Pos']):
        df_hitting_copy[year].drop('Rank', axis = 1, inplace = True)
        df_hitting_copy[year].drop('Cash2023', axis = 1, inplace = True)
        df_hitting_copy[year].drop('Team', axis = 1, inplace = True)
        df_hitting_copy[year].drop('Pos', axis = 1, inplace = True)
    if any(name in df_pitching_copy[year].columns for name in ['Rank','Year','Cash2023','Team','Pos']):
        df_pitching_copy[year].drop('Rank', axis = 1, inplace = True)
        df_pitching_copy[year].drop('Cash2023', axis = 1, inplace = True)
        df_pitching_copy[year].drop('Team', axis = 1, inplace = True)
        df_pitching_copy[year].drop('Pos', axis = 1, inplace = True)

Debido a que aparecen columnas que inician con el  nombre *Unnamed*, tendremos que borrarlas con algún método general, el cual se muestra a continuación:

In [30]:
for year in range(0,period):
    # Base de datos de agentes libres:
    df_free_agents_copy[year].drop(df_free_agents_copy[year].columns[df_free_agents_copy[year].columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
    
    # Base de datos de los salarios:
    df_salary_copy[year].drop(df_salary_copy[year].columns[df_salary_copy[year].columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
    
    # Base de datos de los hitters:
    df_hitting_copy[year].drop(df_hitting_copy[year].columns[df_hitting_copy[year].columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
    
    # Base de datos de los pitchers:
    df_pitching_copy[year].drop(df_pitching_copy[year].columns[df_pitching_copy[year].columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)

Verifiquemos que ya no se encuentran dichas columnas molestas

In [31]:
df_free_agents_copy[9].columns

Index(['Player', 'Status', 'Team From', 'YRS', 'Value', 'AAV'], dtype='object')

In [32]:
df_salary_copy[11].columns

Index(['Player', 'Year', 'Pos', 'Team', 'BaseSalary', 'SigningBonus',
       'Payroll Salary', 'Adj Salary', 'Salary%', 'Cash', 'AAV', 'CONT YR',
       'CONT VALUE', 'Earnings', 'FA Year', 'Sign Age', 'Age', 'Weight',
       'Height'],
      dtype='object')

In [33]:
df_hitting_copy[2].columns

Index(['Player', 'GP', 'GP%', 'GS', 'GS%', 'AB', 'H', '2B', '3B', 'HR', 'RBI',
       'AVG', 'OBP', 'SLG', 'OPS', 'WAR', 'TVS'],
      dtype='object')

In [34]:
df_pitching_copy[5].columns

Index(['Player', 'GP', 'GS', 'IP', 'H', 'R', 'ER', 'BB', 'SO', 'W', 'L', 'SV',
       'WHIP', 'ERA', 'WAR', 'TVS'],
      dtype='object')

#### Agentes libres

No se conservará el equipo al que es contratado el agente libre puesto que esta información también la contiene la base de datos que facilita más el tratamiento _ETL_.

In [35]:
for year in range(0,period):
    df_free_agents_copy[year] = df_free_agents_copy[year].rename(columns = {'Player':'Jugador',
                                'Status':'Status_agente_libre', 'Team From':'Equipo_anterior',
                                'Value':'Valor_contrato', 'AAV':'Valor_promedio_contrato',
                                'YRS':'Anios_de_contrato'})
    
    free_agents_aux_1 = df_free_agents_copy[year]['Valor_contrato'].str.replace("$","")
    free_agents_aux_2 = free_agents_aux_1.str.replace(",","")
    free_agents_aux_3 = df_free_agents_copy[year]['Valor_promedio_contrato'].str.replace("$","")
    free_agents_aux_4 = free_agents_aux_3.str.replace(",","")
    df_free_agents_copy[year]['Valor_contrato'] = free_agents_aux_2
    df_free_agents_copy[year]['Valor_promedio_contrato'] = free_agents_aux_4
    
    df_free_agents_copy[year]['Valor_contrato'] = pd.to_numeric(df_free_agents_copy[year]['Valor_contrato'])
    df_free_agents_copy[year]['Valor_promedio_contrato'] = pd.to_numeric(df_free_agents_copy[year]['Valor_promedio_contrato'])

Observemos las dimensiones de las bases de datos como referencia

In [36]:
for year in range(0,period):
    print(df_free_agents_copy[year].shape)

(1, 6)
(108, 6)
(213, 6)
(208, 6)
(221, 6)
(241, 6)
(100, 6)
(98, 6)
(105, 6)
(118, 6)
(141, 6)
(137, 6)

También el tipo de datos que contiene cada columna

In [37]:
df_free_agents_copy[6].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Jugador                  100 non-null    object
 1   Status_agente_libre      100 non-null    object
 2   Equipo_anterior          100 non-null    object
 3   Anios_de_contrato        100 non-null    int64
 4   Valor_contrato           100 non-null    int64
 5   Valor_promedio_contrato  100 non-null    int64
dtypes: int64(3), object(3)
memory usage: 4.8+ KB

#### Salarios

Como los salarios irán con las bases de datos de los _hitters_ y _pitchers_ es que se hará su proceso _ETL_ antes.

In [38]:
for year in range(0,period):
    # Cambio de nombres
    df_salary_copy[year] = df_salary_copy[year].rename(columns = {'Player':'Jugador',
                            'BaseSalary':'Sueldo_base', 'SigningBonus':'Bono_por_firma',
                            'Payroll Salary':'Sueldo_regular', 'Adj Salary':'Sueldo_ajustado',
                            'CONT YR':'Anios_de_contrato', 'CONT VALUE':'Valor_del_contrato',
                            'Earnings':'Ganancias', 'FA Year':'Anio_de_agente_libre',
                            'Sign Age':'Edad_al_firmar', 'Age':'Edad', 'Weight':'Peso',
                            'Height':'Altura', 'Year':'Anio', 'Pos':'Posicion',
                            'Salary%':'Sueldo_porcentual', 'Cash':'Pago_efectivo',
                            'AAV':'Valor_contrato_promedio', 'Team':'Acronimo'})
    
    # Tranformando al tipo de dato apropiado
    salary_aux_1 = df_salary_copy[year]['Sueldo_base'].str.replace("$","")
    salary_aux_2 = salary_aux_1.str.replace(",","")
    df_salary_copy[year]['Sueldo_base'] = salary_aux_2
    df_salary_copy[year]['Sueldo_base'] = pd.to_numeric(df_salary_copy[year]['Sueldo_base'])
    
    salary_aux_3 = df_salary_copy[year]['Sueldo_regular'].str.replace("$","")
    salary_aux_4 = salary_aux_3.str.replace(",","")
    df_salary_copy[year]['Sueldo_regular'] = salary_aux_4
    df_salary_copy[year]['Sueldo_regular'] = pd.to_numeric(df_salary_copy[year]['Sueldo_regular'])
    
    salary_aux_5 = df_salary_copy[year]['Sueldo_ajustado'].str.replace("$","")
    salary_aux_6 = salary_aux_5.str.replace(",","")
    df_salary_copy[year]['Sueldo_ajustado'] = salary_aux_6
    df_salary_copy[year]['Sueldo_ajustado'] = pd.to_numeric(df_salary_copy[year]['Sueldo_ajustado'])
    
    salary_aux_7 = df_salary_copy[year]['Valor_del_contrato'].str.replace("$","")
    salary_aux_8 = salary_aux_7.str.replace(",","")
    df_salary_copy[year]['Valor_del_contrato'] = salary_aux_8
    df_salary_copy[year]['Valor_del_contrato'] = pd.to_numeric(df_salary_copy[year]['Valor_del_contrato'])
    
    salary_aux_9 = df_salary_copy[year]['Bono_por_firma'].str.replace("$","")
    salary_aux_10 = salary_aux_9.str.replace(",","")
    df_salary_copy[year]['Bono_por_firma'] = salary_aux_10
    df_salary_copy[year]['Bono_por_firma'] = pd.to_numeric(df_salary_copy[year]['Bono_por_firma'])
    
    salary_aux_11 = df_salary_copy[year]['Ganancias'].str.replace("$","")
    salary_aux_12 = salary_aux_11.str.replace(",","")
    df_salary_copy[year]['Ganancias'] = salary_aux_12
    df_salary_copy[year]['Ganancias'] = pd.to_numeric(df_salary_copy[year]['Ganancias'])
    
    salary_aux_13 = df_salary_copy[year]['Pago_efectivo'].str.replace("$","")
    salary_aux_14 = salary_aux_13.str.replace(",","")
    df_salary_copy[year]['Pago_efectivo'] = salary_aux_14
    df_salary_copy[year]['Pago_efectivo'] = pd.to_numeric(df_salary_copy[year]['Pago_efectivo'])
    
    salary_aux_15 = df_salary_copy[year]['Valor_contrato_promedio'].str.replace("$","")
    salary_aux_16 = salary_aux_15.str.replace(",","")
    df_salary_copy[year]['Valor_contrato_promedio'] = salary_aux_16
    df_salary_copy[year]['Valor_contrato_promedio'] = pd.to_numeric(df_salary_copy[year]['Valor_contrato_promedio'])
    
    salary_aux_17 = df_salary_copy[year]['Altura'].str.replace("\"","")
    salary_aux_18 = salary_aux_17.str.replace("'","")
    df_salary_copy[year]['Altura'] = salary_aux_18
    df_salary_copy[year]['Altura'] = pd.to_numeric(df_salary_copy[year]['Altura'])/10
    # SUstitullamos los xeros
    height_mean = df_salary_copy[year]['Altura'].mean(skipna=True)
    df_salary_copy[year]['Altura'] = df_salary_copy[year].Altura.mask(df_salary_copy[year].Altura == 0, height_mean)
    
    df_salary_copy[year]['Anio_de_agente_libre'] = pd.to_numeric(df_salary_copy[year]['Anio_de_agente_libre'])
    df_salary_copy[year]['Anios_de_contrato'] = pd.to_numeric(df_salary_copy[year]['Anios_de_contrato'])
    df_salary_copy[year]['Edad'] = pd.to_numeric(df_salary_copy[year]['Edad'])

Por algunas particularidades de la base de datos, las columna que contiene la edad al firmar se tratará por separado aprovechando que la mayoría de los datos incorrectos tienen una longitud mayor a dos.

In [39]:
for year in range (0,period):
    df_salary_copy[year]['Edad_al_firmar'] = df_salary_copy[year]['Edad_al_firmar'].map(str)

    for edad in range(0,df_salary_copy[year].shape[0]):
        # String es mayor que 0:
        if len(df_salary_copy[year]['Edad_al_firmar'].iloc[edad]) == 2:
            df_salary_copy[year].iloc[edad, df_salary_copy[year].columns.get_loc('Edad_al_firmar')] = pd.to_numeric(df_salary_copy[year]['Edad_al_firmar'].iloc[edad])
            
        # String es menor o igual que 0:
        elif len(df_salary_copy[year]['Edad_al_firmar'].iloc[edad]) != 2:
            # Si la columna de la edad contiene datos correctos
            if df_salary_copy[year]['Edad'].iloc[edad] > 0:
                if df_salary_copy[year]['Anio_de_agente_libre'].iloc[edad] == 0:
                    ag_year = year + 2011 + 1
                else:
                    ag_year = df_salary_copy[year]['Anio_de_agente_libre'].iloc[edad]
                # Get first year of contract
                ini_year = ag_year - df_salary_copy[year]['Anios_de_contrato'].iloc[edad]
                # Años desde el el año inicial
                dif_years = year + 2011 - ini_year
                # Edad al firmar:
                sign_age = df_salary_copy[year]['Edad'].iloc[edad] - dif_years
                # Cambio de dato:
                df_salary_copy[year].iloc[edad, df_salary_copy[year].columns.get_loc('Edad_al_firmar')] = pd.to_numeric(sign_age)
                
            # Si la columna de edad no contiene un dato coherente
            else:
                # Cambio de dato:
                df_salary_copy[year].iloc[edad, df_salary_copy[year].columns.get_loc('Edad_al_firmar')] = pd.to_numeric(18)    
    
        # Entero  menor a 0:
        if df_salary_copy[year]['Edad_al_firmar'].iloc[edad] < 0:
            # Si la columna de la edad contiene datos correctos
            if df_salary_copy[year]['Edad'].iloc[edad] > 0:
                if df_salary_copy[year]['Anio_de_agente_libre'].iloc[edad] == 0:
                    ag_year = year + 2011 + 1
                else:
                    ag_year = df_salary_copy[year]['Anio_de_agente_libre'].iloc[edad]
                # Get first year of contract
                ini_year = ag_year - df_salary_copy[year]['Anios_de_contrato'].iloc[edad]
                # Años desde el el año inicial
                dif_years = year + 2011 - ini_year
                # Edad al firmar:
                sign_age = df_salary_copy[year]['Edad'].iloc[edad] - dif_years
                # Cambio de dato:
                df_salary_copy[year].iloc[edad, df_salary_copy[year].columns.get_loc('Edad_al_firmar')] = pd.to_numeric(sign_age)
                
            # Si la columna de edad no contiene un dato coherente
            else:
                # Cambio de dato:
                df_salary_copy[year].iloc[edad, df_salary_copy[year].columns.get_loc('Edad_al_firmar')] = pd.to_numeric(18)
         
    # Transformemos los datos a enteros
    df_salary_copy[year]['Edad_al_firmar'] = pd.to_numeric(df_salary_copy[year]['Edad_al_firmar'])

Podemos verificar si se limpiaron adecuadamente las celdas de la columna de edades al firmar. Esto, al filtrar los datos que sean distintos a enteros y al observar si se pudo transformar toda la columna al tipo entero.

In [40]:
for year in range(0,period):
    for edad in range(0,df_salary_copy[year]['Edad_al_firmar'].shape[0]):
        if type(df_salary_copy[year]['Edad_al_firmar'].iloc[edad]) != np.int64:
            print(type(df_salary_copy[year]['Edad_al_firmar'].iloc[edad]))

In [41]:
for year in range(0,period):
    for edad in range(0,df_salary_copy[year]['Edad_al_firmar'].shape[0]):
        if df_salary_copy[year]['Edad_al_firmar'].iloc[edad] < 0:
            print(df_salary_copy[year]['Edad_al_firmar'].iloc[edad])

In [42]:
#for year in range(0,period):
#    print(type(df_salary_copy[year][['Edad_al_firmar']].info()))

In [43]:
#for year in range(0,period):
#    print(year)
#    for edad in range(0,df_salary_copy[year]['Edad_al_firmar'].shape[0]):
#        print(str(df_salary_copy[year]['Edad_al_firmar'].iloc[edad]) + ' ' + str(edad))

Por otro lado, falta corregir las entradas de las columnas de las edades que tengan valores menores a cero. Esto se hará de acuerdo al resto de columnas

In [44]:
for year in range(0,period):
    for edad in range(0,df_salary_copy[year]['Edad'].shape[0]):
        if df_salary_copy[year]['Edad'].iloc[edad] < 0:
            print(year)
            print(df_salary_copy[year]['Edad'].iloc[edad])

0
-9
1
-9
2
-7

In [45]:
for year in range(0,period):
    for edad in range(0,df_salary_copy[year].shape[0]):
        # Condición para imputar:
        if df_salary_copy[year]['Edad'].iloc[edad] <= 0:
            # Si no se indica si tendrá año de agencia libre:
            if df_salary_copy[year]['Anio_de_agente_libre'].iloc[edad] == 0:
                        ag_year = year + 2011 + 1
            # Si tendrá año de agencia libre
            else:
                ag_year = df_salary_copy[year]['Anio_de_agente_libre'].iloc[edad]
            # Get first year of contract
            ini_year = ag_year - df_salary_copy[year]['Anios_de_contrato'].iloc[edad]
            # Años desde el el año inicial
            dif_years = year + 2011 - ini_year
            # Edad en la temporada:
            seasson_age = df_salary_copy[year]['Edad_al_firmar'].iloc[edad] + dif_years
            # Asignación
            df_salary_copy[year]['Edad'].iloc[edad] = seasson_age

Comprobemos que no hay ninguna edad negativa

In [46]:
for year in range(0,period):
    for edad in range(0,df_salary_copy[year]['Edad'].shape[0]):
        if df_salary_copy[year]['Edad'].iloc[edad] < 0:
            print(year)
            print(str(df_salary_copy[year]['Edad'].iloc[edad]) + ' ' + str(edad))

Con la imputación de datos ya se puede crear la columna que contiene la antiguedad del agente libre bajo el contrato

In [47]:
for year in range(0,period):
    df_salary_copy[year]['Antiguedad'] = df_salary_copy[year]['Edad'] - df_salary_copy[year]['Edad_al_firmar']

Por último, convirtamos la columna del año a string para que se entienda como una categoría y no una variable numérica

In [48]:
for year in range(0,period):
    df_salary_copy[year]['Anio'] = df_salary_copy[year]['Anio'].map(str)

In [49]:
df_salary_copy[5].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1045 entries, 0 to 1044
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Jugador                  1045 non-null   object
 1   Anio                     1045 non-null   object
 2   Posicion                 1045 non-null   object
 3   Acronimo                 1045 non-null   object
 4   Sueldo_base              1045 non-null   int64
 5   Bono_por_firma           1045 non-null   int64
 6   Sueldo_regular           1045 non-null   int64
 7   Sueldo_ajustado          1045 non-null   int64
 8   Sueldo_porcentual        1045 non-null   float64
 9   Pago_efectivo            1045 non-null   int64
 10  Valor_contrato_promedio  1045 non-null   int64
 11  Anios_de_contrato        1045 non-null   int64
 12  Valor_del_contrato       1045 non-null   int64
 13  Ganancias                1045 non-null   int64
 14  Anio_de_agente_libre     1045 non-null   int64
 15  Edad_al_firmar           1045 non-null   int64
 16  Edad                     1045 non-null   int64
 17  Peso                     1045 non-null   int64
 18  Altura                   1045 non-null   float64
 19  Antiguedad               1045 non-null   int64
dtypes: float64(2), int64(14), object(4)
memory usage: 163.4+ KB

#### Hitters

In [50]:
for year in range(0,period):
    # Cambio de nombres
    df_hitting_copy[year] = df_hitting_copy[year].rename(columns = {'Player':'Jugador',
                            'GP':'Juegos', 'GP%':'Porcentaje_juegos',
                            'AB':'At-bats', 'H':'Bateos', 'GS':'Juegos_iniciados',
                            'GS%':'Porcentaje_juegos_iniciados', 'RBI':'Runs-batted-in',
                            'HR':'Home-runs', 'AVG':'Bateos_promedio',
                            '2B':'Dobles', '3B':'Triples', 'OPS':'Porcentaje_On-base-plus-slugging',
                            'SLG':'Porcentaje_slugging', 'OBP':'Porcentaje_on-base'})

In [51]:
for year in range(0,period):
    print(df_hitting_copy[year].shape)

(521, 17)
(669, 17)
(734, 17)
(778, 17)
(809, 17)
(834, 17)
(810, 17)
(825, 17)
(850, 17)
(451, 17)
(753, 17)
(497, 17)

In [52]:
df_hitting_copy[5].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 834 entries, 0 to 833
Data columns (total 17 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Jugador                           834 non-null    object
 1   Juegos                            834 non-null    int64
 2   Porcentaje_juegos                 834 non-null    float64
 3   Juegos_iniciados                  834 non-null    int64
 4   Porcentaje_juegos_iniciados       834 non-null    float64
 5   At-bats                           834 non-null    int64
 6   Bateos                            834 non-null    int64
 7   Dobles                            834 non-null    int64
 8   Triples                           834 non-null    int64
 9   Home-runs                         834 non-null    int64
 10  Runs-batted-in                    834 non-null    int64
 11  Bateos_promedio                   834 non-null    float64
 12  Porcentaje_on-base                834 non-null    float64
 13  Porcentaje_slugging               834 non-null    float64
 14  Porcentaje_On-base-plus-slugging  834 non-null    float64
 15  WAR                               832 non-null    float64
 16  TVS                               834 non-null    float64
dtypes: float64(8), int64(8), object(1)
memory usage: 110.9+ KB

In [53]:
df_hitting_copy[5].columns

Index(['Jugador', 'Juegos', 'Porcentaje_juegos', 'Juegos_iniciados',
       'Porcentaje_juegos_iniciados', 'At-bats', 'Bateos', 'Dobles', 'Triples',
       'Home-runs', 'Runs-batted-in', 'Bateos_promedio', 'Porcentaje_on-base',
       'Porcentaje_slugging', 'Porcentaje_On-base-plus-slugging', 'WAR',
       'TVS'],
      dtype='object')

#### Pitchers

In [54]:
for year in range(0,period):
    # Cambio de nombres
    df_pitching_copy[year] = df_pitching_copy[year].rename(columns = {'Player':'Jugador',
                             'GP':'Juegos', 'GS':'Juegos_iniciados', 'IP':'Inning_pitched',
                             'H':'Bateos', 'R':'Carreras', 'ER':'Carreras_ganadas',
                             'BB':'Walks', 'SO':'Strike-outs', 'W':'Wins', 'L':'Losses',
                             'SV':'Saves'})

In [55]:
for year in range(0,period):
    print(df_pitching_copy[year].shape)

(1834, 16)
(427, 16)
(485, 16)
(537, 16)
(586, 16)
(592, 16)
(581, 16)
(644, 16)
(668, 16)
(542, 16)
(611, 16)
(598, 16)

In [56]:
df_pitching_copy[5].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592 entries, 0 to 591
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Jugador           592 non-null    object
 1   Juegos            592 non-null    int64
 2   Juegos_iniciados  592 non-null    int64
 3   Inning_pitched    592 non-null    float64
 4   Bateos            592 non-null    int64
 5   Carreras          592 non-null    int64
 6   Carreras_ganadas  592 non-null    int64
 7   Walks             592 non-null    int64
 8   Strike-outs       592 non-null    int64
 9   Wins              592 non-null    int64
 10  Losses            592 non-null    int64
 11  Saves             592 non-null    int64
 12  WHIP              592 non-null    float64
 13  ERA               592 non-null    float64
 14  WAR               587 non-null    float64
 15  TVS               592 non-null    float64
dtypes: float64(5), int64(10), object(1)
memory usage: 74.1+ KB

## Agregación de variables sugeridas por artículos

Las primeras variables que agregaremos son el cuadrado de todas las estadísticas deportivas, así como las siguientes variables:

- DOMINANCE = $Strike-outs/(Inning \; Pitched)$
- CONTROL = $Walks/(Inning \; Pitched)$
- COMMAND = $Strike-outs/Walks$

In [57]:
for year in range(0,period):
    df_pitching_copy[year]['Dominio'] = df_pitching_copy[year]['Strike-outs']/(df_pitching_copy[year]['Inning_pitched'])
    df_pitching_copy[year]['Control'] = df_pitching_copy[year]['Walks']/(df_pitching_copy[year]['Inning_pitched'])
    df_pitching_copy[year]['Comando'] = df_pitching_copy[year]['Strike-outs']/df_pitching_copy[year]['Walks']

In [58]:
for year in range(0,period):
    print(df_pitching_copy[year].shape)

(1834, 19)
(427, 19)
(485, 19)
(537, 19)
(586, 19)
(592, 19)
(581, 19)
(644, 19)
(668, 19)
(542, 19)
(611, 19)
(598, 19)

In [59]:
df_pitching_copy[2].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 485 entries, 0 to 484
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Jugador           485 non-null    object
 1   Juegos            485 non-null    int64
 2   Juegos_iniciados  485 non-null    int64
 3   Inning_pitched    485 non-null    float64
 4   Bateos            485 non-null    int64
 5   Carreras          485 non-null    int64
 6   Carreras_ganadas  485 non-null    int64
 7   Walks             485 non-null    int64
 8   Strike-outs       485 non-null    int64
 9   Wins              485 non-null    int64
 10  Losses            485 non-null    int64
 11  Saves             485 non-null    int64
 12  WHIP              485 non-null    float64
 13  ERA               485 non-null    float64
 14  WAR               435 non-null    float64
 15  TVS               485 non-null    float64
 16  Dominio           484 non-null    float64
 17  Control           485 non-null    float64
 18  Comando           482 non-null    float64
dtypes: float64(8), int64(10), object(1)
memory usage: 72.1+ KB

Podemos verificar qué entradas poseen valores infinitos en la base de datos

In [60]:
"""
for year in range(0,period):
    print(str(2011 + year))
    for name in df_pitching_copy[year].columns:
        print(name)
        if type(name) != str:
            for element in range(0,len(df_pitching_copy[year][name])):
                if math.isinf(df_pitching_copy[year][name].iloc[element]) == True:
                    print(str(element) +  '  ' + str(df_pitching_copy[year][name].iloc[element]))
    print("")
"""

'\nfor year in range(0,period):\n    print(str(2011 + year))\n    for name in df_pitching_copy[year].columns:\n        print(name)\n        if type(name) != str:\n            for element in range(0,len(df_pitching_copy[year][name])):\n                if math.isinf(df_pitching_copy[year][name].iloc[element]) == True:\n                    print(str(element) +  \'  \' + str(df_pitching_copy[year][name].iloc[element]))\n    print("")\n'

Siguiendo la sugerencia de algunos artículos, obtengamos el logaritmo de los salarios

In [61]:
for year in range(0,period):
    df_salary_copy[year]['ln_Sueldo_base'] = np.log(df_salary_copy[year]['Sueldo_base'])
    df_salary_copy[year]['ln_Sueldo_ajustado'] = np.log(df_salary_copy[year]['Sueldo_ajustado'])
    df_salary_copy[year]['ln_Sueldo_regular'] = np.log(df_salary_copy[year]['Sueldo_regular'])

In [62]:
df_salary_copy[2].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1013 entries, 0 to 1012
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Jugador                  1013 non-null   object
 1   Anio                     1013 non-null   object
 2   Posicion                 1013 non-null   object
 3   Acronimo                 1013 non-null   object
 4   Sueldo_base              1013 non-null   int64
 5   Bono_por_firma           1013 non-null   int64
 6   Sueldo_regular           1013 non-null   int64
 7   Sueldo_ajustado          1013 non-null   int64
 8   Sueldo_porcentual        1013 non-null   float64
 9   Pago_efectivo            1013 non-null   int64
 10  Valor_contrato_promedio  1013 non-null   int64
 11  Anios_de_contrato        1013 non-null   int64
 12  Valor_del_contrato       1013 non-null   int64
 13  Ganancias                1013 non-null   int64
 14  Anio_de_agente_libre     1013 non-null   int64
 15  Edad_al_firmar           1013 non-null   int64
 16  Edad                     1013 non-null   int64
 17  Peso                     1013 non-null   int64
 18  Altura                   1013 non-null   float64
 19  Antiguedad               1013 non-null   int64
 20  ln_Sueldo_base           1013 non-null   float64
 21  ln_Sueldo_ajustado       1013 non-null   float64
 22  ln_Sueldo_regular        1013 non-null   float64
dtypes: float64(5), int64(14), object(4)
memory usage: 182.1+ KB

Debido a que hay columnas con datos tipo _Nan_ o _NULL_, optaremos por imputarlos.

Mientras que los valores infinitos generados por las nuevas variables se sustituirán dependediendo del caso:

- 0/0: 0
- num/0: Máximo de la columna correspondientefijarán

In [63]:
for year in range(0,period):
    # Salaries
    mean_hgt = df_salary_copy[year].loc[df_salary_copy[year]['Altura'] > 4.9].Altura.mean()
    mean_wgh = df_salary_copy[year].loc[df_salary_copy[year]['Peso'] > 0].Peso.mean()
    df_salary_copy[year]['Altura'].fillna(value = mean_hgt, inplace = True)
    df_salary_copy[year]['Altura'].mask(df_salary_copy[year]['Altura'] <= 4.9, mean_hgt, inplace = True)
    df_salary_copy[year]['Peso'].fillna(value = mean_wgh, inplace = True)
    df_salary_copy[year]['Peso'].mask(df_salary_copy[year]['Peso'] <= 0, mean_wgh, inplace = True)
    
    # Pitchers
    mean_war = df_pitching_copy[year].loc[df_pitching_copy[year]['WAR'] > 0].WAR.mean()
    mean_dom = df_pitching_copy[year].loc[df_pitching_copy[year]['Dominio'] > 0].Dominio.mean()
    mean_con = df_pitching_copy[year].loc[df_pitching_copy[year]['Control'] > 0].Control.mean()
    mean_com = df_pitching_copy[year].loc[df_pitching_copy[year]['Comando'] > 0].Comando.mean()
    df_pitching_copy[year]['WAR'].fillna(value = mean_war, inplace = True)
    df_pitching_copy[year]['WAR'].mask(df_pitching_copy[year]['WAR'] <= 0, mean_war, inplace = True)
    df_pitching_copy[year]['Dominio'].fillna(value = mean_dom, inplace = True)
    df_pitching_copy[year]['Dominio'].mask(df_pitching_copy[year]['Dominio'] <= 0, mean_dom, inplace = True)
    df_pitching_copy[year]['Control'].fillna(value = mean_con, inplace = True)
    df_pitching_copy[year]['Control'].mask(df_pitching_copy[year]['Control'] <= 0, mean_con, inplace = True)
    df_pitching_copy[year]['Comando'].fillna(value = mean_com, inplace = True)
    df_pitching_copy[year]['Comando'].mask(df_pitching_copy[year]['Comando'] <= 0, mean_com, inplace = True)
    
    # Hitters
    mean_war = df_hitting_copy[year].loc[df_hitting_copy[year]['WAR'] > 0].WAR.mean()
    df_hitting_copy[year]['WAR'].fillna(value = mean_war, inplace = True)
    df_hitting_copy[year]['WAR'].mask(df_hitting_copy[year]['WAR'] <= 0, mean_war, inplace = True)

In [64]:
for year in range(0,period):   
    # Condiciones
    con_dom_1 = df_pitching_copy[year]['Strike-outs'] == 0
    con_con_1 = df_pitching_copy[year]['Walks'] == 0
    con_com_1 = df_pitching_copy[year]['Strike-outs'] == 0
                 
    # Imputación caso 0/0
    df_pitching_copy[year].loc[con_dom_1, "Dominio"] = 0
    df_pitching_copy[year].loc[con_con_1, "Control"] = 0
    df_pitching_copy[year].loc[con_com_1, "Comando"] = 0

In [65]:
for year in range(0,period):   
    # Máximos
    max_dom = df_pitching_copy[year]['Strike-outs'].max()/9
    max_con = df_pitching_copy[year]['Walks'].max()/9
    max_com = df_pitching_copy[year]['Strike-outs'].max()
    
    # Cambianfdo infinitos a NaNs
    df_pitching_copy[year]["Dominio"].replace([np.inf, -np.inf], np.nan, inplace = True)
    df_pitching_copy[year]["Control"].replace([np.inf, -np.inf], np.nan, inplace = True)
    df_pitching_copy[year]["Comando"].replace([np.inf, -np.inf], np.nan, inplace = True)
    
    # Imputación
    df_pitching_copy[year]['Dominio'].fillna(value = max_dom, inplace = True)
    df_pitching_copy[year]['Control'].fillna(value = max_con, inplace = True)
    df_pitching_copy[year]['Comando'].fillna(value = max_com, inplace = True)

Verifiquemos que ya no haya problemas con valores infinitos

In [66]:
"""
for year in range(0,period):
    print(str(2011 + year))
    for name in df_pitching_copy[year].columns:
        print(name)
        if type(name) != str:
            for element in range(0,len(df_pitching_copy[year][name])):
                if math.isinf(df_pitching_copy[year][name].iloc[element]) == True:
                    print(str(element) +  '  ' + str(df_pitching_copy[year][name].iloc[element]))
    print("")
"""

'\nfor year in range(0,period):\n    print(str(2011 + year))\n    for name in df_pitching_copy[year].columns:\n        print(name)\n        if type(name) != str:\n            for element in range(0,len(df_pitching_copy[year][name])):\n                if math.isinf(df_pitching_copy[year][name].iloc[element]) == True:\n                    print(str(element) +  \'  \' + str(df_pitching_copy[year][name].iloc[element]))\n    print("")\n'

Así mismo, contemos los valores *NaN* que queden presentes

In [67]:
for year in range(0,period):
    print('Año: ' + str(2011 + year))
    print('Hitters:')
    df_hitting_copy[year].isna().sum()
    print('Pitchers:')
    df_pitching_copy[year].isna().sum()
    print('Free agents:')
    df_free_agents_copy[year].isna().sum()
    print('Salaries:')
    df_salary_copy[year].isna().sum()
    print("")

Año: 2011
Hitters:
Pitchers:
Free agents:
Salaries:

Año: 2012
Hitters:
Pitchers:
Free agents:
Salaries:

Año: 2013
Hitters:
Pitchers:
Free agents:
Salaries:

Año: 2014
Hitters:
Pitchers:
Free agents:
Salaries:

Año: 2015
Hitters:
Pitchers:
Free agents:
Salaries:

Año: 2016
Hitters:
Pitchers:
Free agents:
Salaries:

Año: 2017
Hitters:
Pitchers:
Free agents:
Salaries:

Año: 2018
Hitters:
Pitchers:
Free agents:
Salaries:

Año: 2019
Hitters:
Pitchers:
Free agents:
Salaries:

Año: 2020
Hitters:
Pitchers:
Free agents:
Salaries:

Año: 2021
Hitters:
Pitchers:
Free agents:
Salaries:

Año: 2022
Hitters:
Pitchers:
Free agents:
Salaries:

Ahora, repitamos este proceso para la base de datos de los salarios.

In [68]:
salary_names = ['ln_Sueldo_ajustado', 'ln_Sueldo_base', 'ln_Sueldo_regular']

In [69]:
for name in salary_names:
    print(name)
    
    for year in range(0,period):
        print(str(2011 + year))
        for element in range(0,len(df_salary_copy[year][name])):
            if df_salary_copy[year][name].iloc[element] <= 0:
                print(str(element) +  '  ' + str(df_salary_copy[year][name].iloc[element]))
        print("")

ln_Sueldo_ajustado
2011

2012

2013

2014

2015

2016

2017

2018
72  -inf
188  -inf

2019

2020

2021
6  -inf
55  -inf
166  -inf
274  -inf

2022
193  -inf

ln_Sueldo_base
2011

2012

2013

2014

2015

2016

2017

2018

2019

2020

2021

2022

ln_Sueldo_regular
2011

2012

2013

2014

2015

2016

2017

2018

2019

2020

2021

2022

Al inspecsionar los errores nos damos cuenta que solo se desconocen los salarios ajustados y los fijaron a $0$. Usaremos el logaritmo base 10 del salario regular para sustituir dicho valor.

In [70]:
for year in range(0,period):
    df_salary_copy[year]['ln_Sueldo_ajustado'].mask(df_salary_copy[year]['ln_Sueldo_ajustado'] < 0,
                                                    df_salary_copy[year]['ln_Sueldo_regular'],
                                                    inplace = True)

In [71]:
for year in range(0,period):
    print(str(2011 + year))
    for element in range(0,len(df_salary_copy[year]['ln_Sueldo_ajustado'])):
        if df_salary_copy[year]['ln_Sueldo_ajustado'].iloc[element] <= 0:
            print(str(element) +  '  ' + str(df_salary_copy[year]['ln_Sueldo_ajustado'].iloc[element]))
    print("")

2011

2012

2013

2014

2015

2016

2017

2018

2019

2020

2021

2022

In [72]:
for year in range(0,period):
    print("Ajustado: " + str(df_salary_copy[year]['ln_Sueldo_ajustado'].mean())
          + 'n'
          + 'Regular: ' + str(df_salary_copy[year]['ln_Sueldo_regular'].mean()))

Ajustado: 13.785784770849762nRegular: 13.888874386883515
Ajustado: 13.81181498978195nRegular: 13.90039782504837
Ajustado: 13.54819591748778nRegular: 13.978975725734408
Ajustado: 13.66411021920866nRegular: 14.080738990191257
Ajustado: 13.49415866539551nRegular: 13.99344595993313
Ajustado: 13.478992231977141nRegular: 14.0261405412466
Ajustado: 13.575363447521962nRegular: 14.079742661574734
Ajustado: 13.562311948859815nRegular: 14.080756222584538
Ajustado: 13.521364643693584nRegular: 14.066559580453122
Ajustado: 13.029458522392627nRegular: 14.216780831796356
Ajustado: 13.70981799580226nRegular: 14.198804602895482
Ajustado: 13.924314685157658nRegular: 14.351734783233747

En efecto, ya no hay valores _NaN_ o _infinitos_.

Con el objetivo de hacer más eficiente la creación de las variables al cuadrado, lo haremos extrayendo el índice de las columnas de interés

In [73]:
df_hitting_copy[0].columns

Index(['Jugador', 'Juegos', 'Porcentaje_juegos', 'Juegos_iniciados',
       'Porcentaje_juegos_iniciados', 'At-bats', 'Bateos', 'Dobles', 'Triples',
       'Home-runs', 'Runs-batted-in', 'Bateos_promedio', 'Porcentaje_on-base',
       'Porcentaje_slugging', 'Porcentaje_On-base-plus-slugging', 'WAR',
       'TVS'],
      dtype='object')

In [74]:
df_pitching_copy[1].columns

Index(['Jugador', 'Juegos', 'Juegos_iniciados', 'Inning_pitched', 'Bateos',
       'Carreras', 'Carreras_ganadas', 'Walks', 'Strike-outs', 'Wins',
       'Losses', 'Saves', 'WHIP', 'ERA', 'WAR', 'TVS', 'Dominio', 'Control',
       'Comando'],
      dtype='object')

In [75]:
def get_col_indices(df, names):
    return df.columns.get_indexer(names)

In [76]:
hitting_names = ['Juegos_iniciados', 'Porcentaje_juegos_iniciados', 'At-bats', 'Bateos',
                  'Dobles', 'Triples', 'Home-runs', 'Runs-batted-in', 'Bateos_promedio',
                  'Porcentaje_on-base', 'Porcentaje_slugging', 'TVS',
                  'Porcentaje_On-base-plus-slugging', 'WAR']	
pitching_names = ['Inning_pitched', 'Bateos', 'Carreras',
                  'Carreras_ganadas', 'Walks', 'Strike-outs', 'Wins', 'Losses',
                  'Saves', 'WHIP', 'ERA', 'WAR', 'TVS', 'Dominio', 'Control',
                  'Comando']

Con el objetivo de simplificar el código, verifiquemos si todos los índices en cada base de datos son los mismos

In [77]:
print('Hitters:')
for year in range(0,period):
    print(get_col_indices(df_hitting_copy[year], hitting_names))
    
print('Pitchers:')
for year in range(0,period):
    print(get_col_indices(df_pitching_copy[year], pitching_names))

Hitters:
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13 16 14 15]
Pitchers:
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]

In [78]:
hitting_indexes = list(get_col_indices(df_hitting_copy[0], hitting_names))
pitching_indexes = list(get_col_indices(df_pitching_copy[0], pitching_names))

In [79]:
for year in range(0,period):
    # Hitters:
    for hitter_name in hitting_indexes:
        df_hitting_copy[year][df_hitting_copy[year].columns[hitter_name] + '_2'] = np.power(df_hitting_copy[year][df_hitting_copy[year].columns[hitter_name]], 2)
    # Pitchers:
    for pitcher_name in pitching_indexes:
        df_pitching_copy[year][df_pitching_copy[year].columns[pitcher_name] + '_2'] = np.power(df_pitching_copy[year][df_pitching_copy[year].columns[pitcher_name]], 2)

Apreciemos el resultado final

In [80]:
df_hitting_copy[2].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734 entries, 0 to 733
Data columns (total 31 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Jugador                             734 non-null    object
 1   Juegos                              734 non-null    int64
 2   Porcentaje_juegos                   734 non-null    float64
 3   Juegos_iniciados                    734 non-null    int64
 4   Porcentaje_juegos_iniciados         734 non-null    float64
 5   At-bats                             734 non-null    int64
 6   Bateos                              734 non-null    int64
 7   Dobles                              734 non-null    int64
 8   Triples                             734 non-null    int64
 9   Home-runs                           734 non-null    int64
 10  Runs-batted-in                      734 non-null    int64
 11  Bateos_promedio                     734 non-null    float64
 12  Porcentaje_on-base                  734 non-null    float64
 13  Porcentaje_slugging                 734 non-null    float64
 14  Porcentaje_On-base-plus-slugging    734 non-null    float64
 15  WAR                                 734 non-null    float64
 16  TVS                                 734 non-null    float64
 17  Juegos_iniciados_2                  734 non-null    int64
 18  Porcentaje_juegos_iniciados_2       734 non-null    float64
 19  At-bats_2                           734 non-null    int64
 20  Bateos_2                            734 non-null    int64
 21  Dobles_2                            734 non-null    int64
 22  Triples_2                           734 non-null    int64
 23  Home-runs_2                         734 non-null    int64
 24  Runs-batted-in_2                    734 non-null    int64
 25  Bateos_promedio_2                   734 non-null    float64
 26  Porcentaje_on-base_2                734 non-null    float64
 27  Porcentaje_slugging_2               734 non-null    float64
 28  TVS_2                               734 non-null    float64
 29  Porcentaje_On-base-plus-slugging_2  734 non-null    float64
 30  WAR_2                               734 non-null    float64
dtypes: float64(15), int64(15), object(1)
memory usage: 177.9+ KB

In [81]:
df_pitching_copy[2].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 485 entries, 0 to 484
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Jugador             485 non-null    object
 1   Juegos              485 non-null    int64
 2   Juegos_iniciados    485 non-null    int64
 3   Inning_pitched      485 non-null    float64
 4   Bateos              485 non-null    int64
 5   Carreras            485 non-null    int64
 6   Carreras_ganadas    485 non-null    int64
 7   Walks               485 non-null    int64
 8   Strike-outs         485 non-null    int64
 9   Wins                485 non-null    int64
 10  Losses              485 non-null    int64
 11  Saves               485 non-null    int64
 12  WHIP                485 non-null    float64
 13  ERA                 485 non-null    float64
 14  WAR                 485 non-null    float64
 15  TVS                 485 non-null    float64
 16  Dominio             485 non-null    float64
 17  Control             485 non-null    float64
 18  Comando             485 non-null    float64
 19  Inning_pitched_2    485 non-null    float64
 20  Bateos_2            485 non-null    int64
 21  Carreras_2          485 non-null    int64
 22  Carreras_ganadas_2  485 non-null    int64
 23  Walks_2             485 non-null    int64
 24  Strike-outs_2       485 non-null    int64
 25  Wins_2              485 non-null    int64
 26  Losses_2            485 non-null    int64
 27  Saves_2             485 non-null    int64
 28  WHIP_2              485 non-null    float64
 29  ERA_2               485 non-null    float64
 30  WAR_2               485 non-null    float64
 31  TVS_2               485 non-null    float64
 32  Dominio_2           485 non-null    float64
 33  Control_2           485 non-null    float64
 34  Comando_2           485 non-null    float64
dtypes: float64(16), int64(18), object(1)
memory usage: 132.7+ KB

## Unión de las bases de datos
### Datos agregados por equipo

Solo resta añadir los datos relevantes al equipo al que pertenece cada jugador considerando la base de datos de la cantidad de equipos por estado

In [82]:
df_teams_copy[7].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Equipo                   28 non-null     object
 1   Cantidad_agentes_libres  28 non-null     int64
 2   Valor_contrato_total     28 non-null     int64
 3   Acronimo                 28 non-null     object
 4   Victorias                28 non-null     int64
 5   Juegos totales           28 non-null     int64
 6   Playoffs                 28 non-null     int64
 7   Pennants won             28 non-null     int64
 8   WS ganadas               28 non-null     int64
 9   Promedio_victorias       28 non-null     float64
dtypes: float64(1), int64(7), object(2)
memory usage: 2.3+ KB

In [83]:
acronym_state.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Estado               30 non-null     object
 1   Cantidad de equipos  30 non-null     int64
 2   Equipo               30 non-null     object
 3   Acronimo             30 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.2+ KB

In [84]:
for year in range(0,period):
    df_teams_copy[year] = pd.merge(df_teams_copy[year], acronym_state, on = ['Equipo','Acronimo'])

In [85]:
df_teams_copy[7].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28 entries, 0 to 27
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Equipo                   28 non-null     object
 1   Cantidad_agentes_libres  28 non-null     int64
 2   Valor_contrato_total     28 non-null     int64
 3   Acronimo                 28 non-null     object
 4   Victorias                28 non-null     int64
 5   Juegos totales           28 non-null     int64
 6   Playoffs                 28 non-null     int64
 7   Pennants won             28 non-null     int64
 8   WS ganadas               28 non-null     int64
 9   Promedio_victorias       28 non-null     float64
 10  Estado                   28 non-null     object
 11  Cantidad de equipos      28 non-null     int64
dtypes: float64(1), int64(8), object(3)
memory usage: 2.8+ KB

In [86]:
df_salary_copy[7].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1036 entries, 0 to 1035
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Jugador                  1036 non-null   object
 1   Anio                     1036 non-null   object
 2   Posicion                 1036 non-null   object
 3   Acronimo                 1036 non-null   object
 4   Sueldo_base              1036 non-null   int64
 5   Bono_por_firma           1036 non-null   int64
 6   Sueldo_regular           1036 non-null   int64
 7   Sueldo_ajustado          1036 non-null   int64
 8   Sueldo_porcentual        1036 non-null   float64
 9   Pago_efectivo            1036 non-null   int64
 10  Valor_contrato_promedio  1036 non-null   int64
 11  Anios_de_contrato        1036 non-null   int64
 12  Valor_del_contrato       1036 non-null   int64
 13  Ganancias                1036 non-null   int64
 14  Anio_de_agente_libre     1036 non-null   int64
 15  Edad_al_firmar           1036 non-null   int64
 16  Edad                     1036 non-null   int64
 17  Peso                     1036 non-null   float64
 18  Altura                   1036 non-null   float64
 19  Antiguedad               1036 non-null   int64
 20  ln_Sueldo_base           1036 non-null   float64
 21  ln_Sueldo_ajustado       1036 non-null   float64
 22  ln_Sueldo_regular        1036 non-null   float64
dtypes: float64(6), int64(13), object(4)
memory usage: 186.3+ KB

Ahora, unamos las bases de datos sobre los equipos a las bases de datos de los salarios

In [87]:
for year in range(0,period):
    df_salary_copy[year] = pd.merge(df_teams_copy[year], df_salary_copy[year], on = 'Acronimo')

In [88]:
df_salary_copy[0].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40 entries, 0 to 39
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Equipo                   40 non-null     object
 1   Cantidad_agentes_libres  40 non-null     int64
 2   Valor_contrato_total     40 non-null     int64
 3   Acronimo                 40 non-null     object
 4   Victorias                40 non-null     int64
 5   Juegos totales           40 non-null     int64
 6   Playoffs                 40 non-null     int64
 7   Pennants won             40 non-null     int64
 8   WS ganadas               40 non-null     int64
 9   Promedio_victorias       40 non-null     float64
 10  Estado                   40 non-null     object
 11  Cantidad de equipos      40 non-null     int64
 12  Jugador                  40 non-null     object
 13  Anio                     40 non-null     object
 14  Posicion                 40 non-null     object
 15  Sueldo_base              40 non-null     int64
 16  Bono_por_firma           40 non-null     int64
 17  Sueldo_regular           40 non-null     int64
 18  Sueldo_ajustado          40 non-null     int64
 19  Sueldo_porcentual        40 non-null     float64
 20  Pago_efectivo            40 non-null     int64
 21  Valor_contrato_promedio  40 non-null     int64
 22  Anios_de_contrato        40 non-null     int64
 23  Valor_del_contrato       40 non-null     int64
 24  Ganancias                40 non-null     int64
 25  Anio_de_agente_libre     40 non-null     int64
 26  Edad_al_firmar           40 non-null     int64
 27  Edad                     40 non-null     int64
 28  Peso                     40 non-null     float64
 29  Altura                   40 non-null     float64
 30  Antiguedad               40 non-null     int64
 31  ln_Sueldo_base           40 non-null     float64
 32  ln_Sueldo_ajustado       40 non-null     float64
 33  ln_Sueldo_regular        40 non-null     float64
dtypes: float64(7), int64(21), object(6)
memory usage: 10.9+ KB

Debido a que la mayoría de los jugadores juega tanto en la ofensiva como la defensiva es que tenemos que borrar los duplicados de la columna de la posición.

In [89]:
for year in range(0,period):
    df_hitting_copy[year] = pd.merge(df_hitting_copy[year], df_salary_copy[year], on = 'Jugador')
    df_pitching_copy[year] = pd.merge(df_pitching_copy[year], df_salary_copy[year], on = 'Jugador')

In [90]:
for year in range(0,period):
    df_pitching_copy[year]['Porcentaje_juegos'] = df_pitching_copy[year]['Juegos']/df_pitching_copy[year]['Juegos totales']

In [91]:
df_hitting_copy[3].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 668 entries, 0 to 667
Data columns (total 64 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Jugador                             668 non-null    object
 1   Juegos                              668 non-null    int64
 2   Porcentaje_juegos                   668 non-null    float64
 3   Juegos_iniciados                    668 non-null    int64
 4   Porcentaje_juegos_iniciados         668 non-null    float64
 5   At-bats                             668 non-null    int64
 6   Bateos                              668 non-null    int64
 7   Dobles                              668 non-null    int64
 8   Triples                             668 non-null    int64
 9   Home-runs                           668 non-null    int64
 10  Runs-batted-in                      668 non-null    int64
 11  Bateos_promedio                     668 non-null    float64
 12  Porcentaje_on-base                  668 non-null    float64
 13  Porcentaje_slugging                 668 non-null    float64
 14  Porcentaje_On-base-plus-slugging    668 non-null    float64
 15  WAR                                 668 non-null    float64
 16  TVS                                 668 non-null    float64
 17  Juegos_iniciados_2                  668 non-null    int64
 18  Porcentaje_juegos_iniciados_2       668 non-null    float64
 19  At-bats_2                           668 non-null    int64
 20  Bateos_2                            668 non-null    int64
 21  Dobles_2                            668 non-null    int64
 22  Triples_2                           668 non-null    int64
 23  Home-runs_2                         668 non-null    int64
 24  Runs-batted-in_2                    668 non-null    int64
 25  Bateos_promedio_2                   668 non-null    float64
 26  Porcentaje_on-base_2                668 non-null    float64
 27  Porcentaje_slugging_2               668 non-null    float64
 28  TVS_2                               668 non-null    float64
 29  Porcentaje_On-base-plus-slugging_2  668 non-null    float64
 30  WAR_2                               668 non-null    float64
 31  Equipo                              668 non-null    object
 32  Cantidad_agentes_libres             668 non-null    int64
 33  Valor_contrato_total                668 non-null    int64
 34  Acronimo                            668 non-null    object
 35  Victorias                           668 non-null    int64
 36  Juegos totales                      668 non-null    int64
 37  Playoffs                            668 non-null    int64
 38  Pennants won                        668 non-null    int64
 39  WS ganadas                          668 non-null    int64
 40  Promedio_victorias                  668 non-null    float64
 41  Estado                              668 non-null    object
 42  Cantidad de equipos                 668 non-null    int64
 43  Anio                                668 non-null    object
 44  Posicion                            668 non-null    object
 45  Sueldo_base                         668 non-null    int64
 46  Bono_por_firma                      668 non-null    int64
 47  Sueldo_regular                      668 non-null    int64
 48  Sueldo_ajustado                     668 non-null    int64
 49  Sueldo_porcentual                   668 non-null    float64
 50  Pago_efectivo                       668 non-null    int64
 51  Valor_contrato_promedio             668 non-null    int64
 52  Anios_de_contrato                   668 non-null    int64
 53  Valor_del_contrato                  668 non-null    int64
 54  Ganancias                           668 non-null    int64
 55  Anio_de_agente_libre                668 non-null    int64
 56  Edad_al_firmar                      668 non-null    int64
 57  Edad                                668 non-null    int64
 58  Peso                                668 non-null    float64
 59  Altura                              668 non-null    float64
 60  Antiguedad                          668 non-null    int64
 61  ln_Sueldo_base                      668 non-null    float64
 62  ln_Sueldo_ajustado                  668 non-null    float64
 63  ln_Sueldo_regular                   668 non-null    float64
dtypes: float64(22), int64(36), object(6)
memory usage: 339.2+ KB

In [92]:
df_pitching_copy[3].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 497 entries, 0 to 496
Data columns (total 69 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Jugador                  497 non-null    object
 1   Juegos                   497 non-null    int64
 2   Juegos_iniciados         497 non-null    int64
 3   Inning_pitched           497 non-null    float64
 4   Bateos                   497 non-null    int64
 5   Carreras                 497 non-null    int64
 6   Carreras_ganadas         497 non-null    int64
 7   Walks                    497 non-null    int64
 8   Strike-outs              497 non-null    int64
 9   Wins                     497 non-null    int64
 10  Losses                   497 non-null    int64
 11  Saves                    497 non-null    int64
 12  WHIP                     497 non-null    float64
 13  ERA                      497 non-null    float64
 14  WAR                      497 non-null    float64
 15  TVS                      497 non-null    float64
 16  Dominio                  497 non-null    float64
 17  Control                  497 non-null    float64
 18  Comando                  497 non-null    float64
 19  Inning_pitched_2         497 non-null    float64
 20  Bateos_2                 497 non-null    int64
 21  Carreras_2               497 non-null    int64
 22  Carreras_ganadas_2       497 non-null    int64
 23  Walks_2                  497 non-null    int64
 24  Strike-outs_2            497 non-null    int64
 25  Wins_2                   497 non-null    int64
 26  Losses_2                 497 non-null    int64
 27  Saves_2                  497 non-null    int64
 28  WHIP_2                   497 non-null    float64
 29  ERA_2                    497 non-null    float64
 30  WAR_2                    497 non-null    float64
 31  TVS_2                    497 non-null    float64
 32  Dominio_2                497 non-null    float64
 33  Control_2                497 non-null    float64
 34  Comando_2                497 non-null    float64
 35  Equipo                   497 non-null    object
 36  Cantidad_agentes_libres  497 non-null    int64
 37  Valor_contrato_total     497 non-null    int64
 38  Acronimo                 497 non-null    object
 39  Victorias                497 non-null    int64
 40  Juegos totales           497 non-null    int64
 41  Playoffs                 497 non-null    int64
 42  Pennants won             497 non-null    int64
 43  WS ganadas               497 non-null    int64
 44  Promedio_victorias       497 non-null    float64
 45  Estado                   497 non-null    object
 46  Cantidad de equipos      497 non-null    int64
 47  Anio                     497 non-null    object
 48  Posicion                 497 non-null    object
 49  Sueldo_base              497 non-null    int64
 50  Bono_por_firma           497 non-null    int64
 51  Sueldo_regular           497 non-null    int64
 52  Sueldo_ajustado          497 non-null    int64
 53  Sueldo_porcentual        497 non-null    float64
 54  Pago_efectivo            497 non-null    int64
 55  Valor_contrato_promedio  497 non-null    int64
 56  Anios_de_contrato        497 non-null    int64
 57  Valor_del_contrato       497 non-null    int64
 58  Ganancias                497 non-null    int64
 59  Anio_de_agente_libre     497 non-null    int64
 60  Edad_al_firmar           497 non-null    int64
 61  Edad                     497 non-null    int64
 62  Peso                     497 non-null    float64
 63  Altura                   497 non-null    float64
 64  Antiguedad               497 non-null    int64
 65  ln_Sueldo_base           497 non-null    float64
 66  ln_Sueldo_ajustado       497 non-null    float64
 67  ln_Sueldo_regular        497 non-null    float64
 68  Porcentaje_juegos        497 non-null    float64
dtypes: float64(24), int64(39), object(6)
memory usage: 271.8+ KB

Para facilitar la observación de las trnasformaciones de manera más eficiente, ordenemos alfabéticamente la base de datos de acuerdo al nombre de las columnas.

In [93]:
for year in range(0,period):
    # Ordenando alfabéticamente
    df_salary_copy[year].sort_index(axis = 1, inplace = True)
    df_hitting_copy[year].sort_index(axis = 1, inplace = True)
    df_pitching_copy[year].sort_index(axis = 1, inplace = True)
    df_free_agents_copy[year].sort_index(axis = 1, inplace = True)
    
    # Reiniciando los índices
    df_salary_copy[year].reset_index(drop = True, inplace = True)
    df_hitting_copy[year].reset_index(drop = True, inplace = True)
    df_pitching_copy[year].reset_index(drop = True, inplace = True)
    df_free_agents_copy[year].reset_index(drop = True, inplace = True)

## Variables del periodo t-1

Lo que haremos será un *merge* de las bases de datos del año $t$ con el año $t-1$ sobre los jugadores. La razón de esto es que solo nos interesan los jugadores que han sido agentes libres por más de un año.

Si la primera base de datos es del año 2011, entonces tendremos que empezar en el año 2012. Creemos los dataframes que contendrán los datos para el modelo. Para que no se sobrepongan todos los periodos, crearemos dataframes auxiliares para guardar los nuevos datos

In [94]:
hitting_merge = ['Juegos_iniciados', 'Porcentaje_juegos_iniciados', 'At-bats', 'Bateos',
                 'Dobles', 'Triples', 'Home-runs', 'Runs-batted-in', 'Bateos_promedio',
                 'Porcentaje_on-base', 'Porcentaje_slugging', 'TVS',
                 'Porcentaje_On-base-plus-slugging', 'WAR',
                 'Juegos_iniciados_2', 'Porcentaje_juegos_iniciados_2', 'At-bats_2', 'Bateos_2',
                 'Dobles_2', 'Triples_2', 'Home-runs_2', 'Runs-batted-in_2', 'Bateos_promedio_2',
                 'Porcentaje_on-base_2', 'Porcentaje_slugging_2', 'TVS_2',
                 'Porcentaje_On-base-plus-slugging_2', 'WAR_2']	
pitching_merge = ['Inning_pitched', 'Bateos_en_contra', 'Carreras_en_contra',
                  'Carreras_ganadas', 'Walks', 'Strike-outs', 'Wins', 'Losses',
                  'Saves', 'WHIP', 'ERA', 'WAR', 'TVS', 'Dominio', 'Control',
                  'Comando',
                  'Inning_pitched_2', 'Bateos_2', 'Carreras_2',
                  'Carreras_ganadas_2', 'Walks_2', 'Strike-outs_2', 'Wins_2', 'Losses_2',
                  'Saves_2', 'WHIP_2', 'ERA_2', 'WAR_2', 'TVS_2', 'Dominio_2', 'Control_2',
                  'Comando_2']

In [95]:
df_hitters_copy = [None]*period
df_pitchers_copy = [None]*period

In [96]:
for year in range(0,period):
    df_hitters_copy[year] = df_hitting_copy[year].copy()
    df_pitchers_copy[year] = df_pitching_copy[year].copy()

In [97]:
for year in range(1,period):    
    df_hitting_copy[year] = pd.merge(df_hitters_copy[year], df_hitters_copy[year-1], on = 'Jugador')
    df_pitching_copy[year] = pd.merge(df_pitchers_copy[year], df_pitchers_copy[year-1], on = 'Jugador')

A continuación se verifica que la cantidad de columnas sea la misma, salvo por el primer periodo

In [98]:
"""for name in df_pitching_copy[11].columns:
    print(name)"""

'for name in df_pitching_copy[11].columns:\n    print(name)'

In [99]:
for year in range(0,period):
    print(df_hitting_copy[year].columns.shape)
    
for year in range(0,period):    
    print(df_pitching_copy[year].columns.shape)

(64,)
(127,)
(127,)
(127,)
(127,)
(127,)
(127,)
(127,)
(127,)
(127,)
(127,)
(127,)
(69,)
(137,)
(137,)
(137,)
(137,)
(137,)
(137,)
(137,)
(137,)
(137,)
(137,)
(137,)

In [100]:
for year in range(1,period):       
    df_pitching_copy[year].columns = df_pitching_copy[year].columns.str.replace('_x', '_t')
    df_pitching_copy[year].columns = df_pitching_copy[year].columns.str.replace('_y', '_t_1')
    df_pitching_copy[year].columns = df_pitching_copy[year].columns.str.replace('-', '_')
    df_pitching_copy[year].columns = df_pitching_copy[year].columns.str.replace(' ', '_')
    df_pitching_copy[year].drop(['ln_Sueldo_base_t_1', 'ln_Sueldo_ajustado_t_1', 'ln_Sueldo_regular_t_1'],
                           axis = 1, inplace = True)
    df_pitching_copy[year] = df_pitching_copy[year].sort_values(by = 'Jugador', ascending = True)
    df_pitching_copy[year].reset_index(drop = True, inplace = True)
    
    df_hitting_copy[year].columns = df_hitting_copy[year].columns.str.replace('_x', '_t')
    df_hitting_copy[year].columns = df_hitting_copy[year].columns.str.replace('_y', '_t_1')
    df_hitting_copy[year].columns = df_hitting_copy[year].columns.str.replace('-', '_')
    df_hitting_copy[year].columns = df_hitting_copy[year].columns.str.replace(' ', '_')
    df_hitting_copy[year].drop(['ln_Sueldo_base_t_1', 'ln_Sueldo_ajustado_t_1', 'ln_Sueldo_regular_t_1'],
                          axis = 1, inplace = True)
    df_hitting_copy[year] = df_hitting_copy[year].sort_values(by = 'Jugador', ascending = True)
    df_hitting_copy[year].reset_index(drop = True, inplace = True)
    
    # Reordenando las columnas
    df_hitting_copy[year].sort_index(axis = 1, inplace = True)
    df_pitching_copy[year].sort_index(axis = 1, inplace = True)

In [101]:
for name in df_pitching_copy[11].columns:
    print(name)

Acronimo_t
Acronimo_t_1
Altura_t
Altura_t_1
Anio_de_agente_libre_t
Anio_de_agente_libre_t_1
Anio_t
Anio_t_1
Anios_de_contrato_t
Anios_de_contrato_t_1
Antiguedad_t
Antiguedad_t_1
Bateos_2_t
Bateos_2_t_1
Bateos_t
Bateos_t_1
Bono_por_firma_t
Bono_por_firma_t_1
Cantidad_agentes_libres_t
Cantidad_agentes_libres_t_1
Cantidad_de_equipos_t
Cantidad_de_equipos_t_1
Carreras_2_t
Carreras_2_t_1
Carreras_ganadas_2_t
Carreras_ganadas_2_t_1
Carreras_ganadas_t
Carreras_ganadas_t_1
Carreras_t
Carreras_t_1
Comando_2_t
Comando_2_t_1
Comando_t
Comando_t_1
Control_2_t
Control_2_t_1
Control_t
Control_t_1
Dominio_2_t
Dominio_2_t_1
Dominio_t
Dominio_t_1
ERA_2_t
ERA_2_t_1
ERA_t
ERA_t_1
Edad_al_firmar_t
Edad_al_firmar_t_1
Edad_t
Edad_t_1
Equipo_t
Equipo_t_1
Estado_t
Estado_t_1
Ganancias_t
Ganancias_t_1
Inning_pitched_2_t
Inning_pitched_2_t_1
Inning_pitched_t
Inning_pitched_t_1
Juegos_iniciados_t
Juegos_iniciados_t_1
Juegos_t
Juegos_t_1
Juegos_totales_t
Juegos_totales_t_1
Jugador
Losses_2_t
Losses_2_t_1
Losses_t
Losses_t_1
Pago_efectivo_t
Pago_efectivo_t_1
Pennants_won_t
Pennants_won_t_1
Peso_t
Peso_t_1
Playoffs_t
Playoffs_t_1
Porcentaje_juegos_t
Porcentaje_juegos_t_1
Posicion_t
Posicion_t_1
Promedio_victorias_t
Promedio_victorias_t_1
Saves_2_t
Saves_2_t_1
Saves_t
Saves_t_1
Strike_outs_2_t
Strike_outs_2_t_1
Strike_outs_t
Strike_outs_t_1
Sueldo_ajustado_t
Sueldo_ajustado_t_1
Sueldo_base_t
Sueldo_base_t_1
Sueldo_porcentual_t
Sueldo_porcentual_t_1
Sueldo_regular_t
Sueldo_regular_t_1
TVS_2_t
TVS_2_t_1
TVS_t
TVS_t_1
Valor_contrato_promedio_t
Valor_contrato_promedio_t_1
Valor_contrato_total_t
Valor_contrato_total_t_1
Valor_del_contrato_t
Valor_del_contrato_t_1
Victorias_t
Victorias_t_1
WAR_2_t
WAR_2_t_1
WAR_t
WAR_t_1
WHIP_2_t
WHIP_2_t_1
WHIP_t
WHIP_t_1
WS_ganadas_t
WS_ganadas_t_1
Walks_2_t
Walks_2_t_1
Walks_t
Walks_t_1
Wins_2_t
Wins_2_t_1
Wins_t
Wins_t_1
ln_Sueldo_ajustado_t
ln_Sueldo_base_t
ln_Sueldo_regular_t

Debido a que muchas de las variables del periodo $t_1$ pueden funcionar como controles más realistas, se optarán por dejarlas a excepción de la columna que contiene el dato del año al que hace referencia el dataframe del periodo $t_1$, es decir, la columna *Anio_t_1*. Esto se hará para *pitchers* y *hitters*. Por razones análogas, también de omitirá la columna que indica la cantidad de equipos en determinado estado ya que en el periodo de análisis es invariante.

Para facilitar la escritura del código, entenderemos la columna *Anio* como la columna *Anio_t*.

In [102]:
for year in range(1,period):
    df_pitching_copy[year].drop(['Anio_t_1', 'Estado_t_1', 'Edad_t_1'],
                           axis = 1, inplace = True)
    
    df_hitting_copy[year].drop(['Anio_t_1', 'Estado_t_1', 'Edad_t_1'],
                           axis = 1, inplace = True)
    
    # Reordenando las columnas
    df_hitting_copy[year].sort_index(axis = 1, inplace = True)
    df_pitching_copy[year].sort_index(axis = 1, inplace = True)
    
    # Reiniciando índice
    df_hitting_copy[year].reset_index(drop = True, inplace = True)
    df_pitching_copy[year].reset_index(drop = True, inplace = True)

Cambiemos el súfijo de las basses de datos del año del 2011

In [103]:
year = 0
# Reiniciando los índices
df_hitting_copy[year] = df_hitting_copy[year].add_suffix('_t')
df_pitching_copy[year] = df_pitching_copy[year].add_suffix('_t')
# Corrección de columna del jugador
df_hitting_copy[year].columns = df_hitting_copy[year].columns.str.replace('Jugador_t', 'Jugador')
df_pitching_copy[year].columns = df_pitching_copy[year].columns.str.replace('Jugador_t', 'Jugador')

In [104]:
print("Salarios")
print(df_salary_copy[year].columns)
print("\n")
print("Hitters")
print(df_hitting_copy[year].columns)
print("\n")
print("Pitchers")
print(df_pitching_copy[year].columns)
print("\n")
print("Free agents")
print(df_free_agents_copy[year].columns)
print("\n")

Salarios
Index(['Acronimo', 'Altura', 'Anio', 'Anio_de_agente_libre',
       'Anios_de_contrato', 'Antiguedad', 'Bono_por_firma',
       'Cantidad de equipos', 'Cantidad_agentes_libres', 'Edad',
       'Edad_al_firmar', 'Equipo', 'Estado', 'Ganancias', 'Juegos totales',
       'Jugador', 'Pago_efectivo', 'Pennants won', 'Peso', 'Playoffs',
       'Posicion', 'Promedio_victorias', 'Sueldo_ajustado', 'Sueldo_base',
       'Sueldo_porcentual', 'Sueldo_regular', 'Valor_contrato_promedio',
       'Valor_contrato_total', 'Valor_del_contrato', 'Victorias', 'WS ganadas',
       'ln_Sueldo_ajustado', 'ln_Sueldo_base', 'ln_Sueldo_regular'],
      dtype='object')


Hitters
Index(['Acronimo_t', 'Altura_t', 'Anio_t', 'Anio_de_agente_libre_t',
       'Anios_de_contrato_t', 'Antiguedad_t', 'At-bats_t', 'At-bats_2_t',
       'Bateos_t', 'Bateos_2_t', 'Bateos_promedio_t', 'Bateos_promedio_2_t',
       'Bono_por_firma_t', 'Cantidad de equipos_t',
       'Cantidad_agentes_libres_t', 'Dobles_t', 'Dobles_2_t', 'Edad_t',
       'Edad_al_firmar_t', 'Equipo_t', 'Estado_t', 'Ganancias_t',
       'Home-runs_t', 'Home-runs_2_t', 'Juegos_t', 'Juegos totales_t',
       'Juegos_iniciados_t', 'Juegos_iniciados_2_t', 'Jugador',
       'Pago_efectivo_t', 'Pennants won_t', 'Peso_t', 'Playoffs_t',
       'Porcentaje_On-base-plus-slugging_t',
       'Porcentaje_On-base-plus-slugging_2_t', 'Porcentaje_juegos_t',
       'Porcentaje_juegos_iniciados_t', 'Porcentaje_juegos_iniciados_2_t',
       'Porcentaje_on-base_t', 'Porcentaje_on-base_2_t',
       'Porcentaje_slugging_t', 'Porcentaje_slugging_2_t', 'Posicion_t',
       'Promedio_victorias_t', 'Runs-batted-in_t', 'Runs-batted-in_2_t',
       'Sueldo_ajustado_t', 'Sueldo_base_t', 'Sueldo_porcentual_t',
       'Sueldo_regular_t', 'TVS_t', 'TVS_2_t', 'Triples_t', 'Triples_2_t',
       'Valor_contrato_promedio_t', 'Valor_contrato_total_t',
       'Valor_del_contrato_t', 'Victorias_t', 'WAR_t', 'WAR_2_t',
       'WS ganadas_t', 'ln_Sueldo_ajustado_t', 'ln_Sueldo_base_t',
       'ln_Sueldo_regular_t'],
      dtype='object')


Pitchers
Index(['Acronimo_t', 'Altura_t', 'Anio_t', 'Anio_de_agente_libre_t',
       'Anios_de_contrato_t', 'Antiguedad_t', 'Bateos_t', 'Bateos_2_t',
       'Bono_por_firma_t', 'Cantidad de equipos_t',
       'Cantidad_agentes_libres_t', 'Carreras_t', 'Carreras_2_t',
       'Carreras_ganadas_t', 'Carreras_ganadas_2_t', 'Comando_t',
       'Comando_2_t', 'Control_t', 'Control_2_t', 'Dominio_t', 'Dominio_2_t',
       'ERA_t', 'ERA_2_t', 'Edad_t', 'Edad_al_firmar_t', 'Equipo_t',
       'Estado_t', 'Ganancias_t', 'Inning_pitched_t', 'Inning_pitched_2_t',
       'Juegos_t', 'Juegos totales_t', 'Juegos_iniciados_t', 'Jugador',
       'Losses_t', 'Losses_2_t', 'Pago_efectivo_t', 'Pennants won_t', 'Peso_t',
       'Playoffs_t', 'Porcentaje_juegos_t', 'Posicion_t',
       'Promedio_victorias_t', 'Saves_t', 'Saves_2_t', 'Strike-outs_t',
       'Strike-outs_2_t', 'Sueldo_ajustado_t', 'Sueldo_base_t',
       'Sueldo_porcentual_t', 'Sueldo_regular_t', 'TVS_t', 'TVS_2_t',
       'Valor_contrato_promedio_t', 'Valor_contrato_total_t',
       'Valor_del_contrato_t', 'Victorias_t', 'WAR_t', 'WAR_2_t', 'WHIP_t',
       'WHIP_2_t', 'WS ganadas_t', 'Walks_t', 'Walks_2_t', 'Wins_t',
       'Wins_2_t', 'ln_Sueldo_ajustado_t', 'ln_Sueldo_base_t',
       'ln_Sueldo_regular_t'],
      dtype='object')


Free agents
Index(['Anios_de_contrato', 'Equipo_anterior', 'Jugador',
       'Status_agente_libre', 'Valor_contrato', 'Valor_promedio_contrato'],
      dtype='object')

## Segmentación por Agentes libres

Separaremos los pitchers y hitters en dos grupos:

- Agentes libres.
- No agentes libres.

In [105]:
for year in range(0,period):
    # Filtrando los agentes libres
    df_hitters_free_agents[year] = pd.merge(df_free_agents_copy[year],
                                            df_hitting_copy[year], on = 'Jugador')
    df_pitchers_free_agents[year] = pd.merge(df_free_agents_copy[year],
                                             df_pitching_copy[year], on = 'Jugador')
    # FIltrando los que no son agentes libres
    df_hitters_no_free_agents[year] = df_hitting_copy[year][~df_hitting_copy[year].Jugador.isin(df_hitters_free_agents[year].Jugador)]
    df_pitchers_no_free_agents[year] = df_pitching_copy[year][~df_pitching_copy[year].Jugador.isin(df_pitchers_free_agents[year].Jugador)]
    
    # Reiniciando el índice
    df_hitters_free_agents[year] = df_hitters_free_agents[year].reindex(sorted(df_hitters_free_agents[year].columns), axis=1)
    df_pitchers_free_agents[year] = df_pitchers_free_agents[year].reindex(sorted(df_pitchers_free_agents[year].columns), axis=1)
    df_hitters_no_free_agents[year] = df_hitters_no_free_agents[year].reindex(sorted(df_hitters_no_free_agents[year].columns), axis=1)
    df_pitchers_no_free_agents[year] = df_pitchers_no_free_agents[year].reindex(sorted(df_pitchers_no_free_agents[year].columns), axis=1)

Veamos los contenidos de las nuevas bases de datos

In [106]:
print("FA - Hitters:")
df_hitters_free_agents[9].info()
print("\n FA - Pitchers:")
df_pitchers_free_agents[9].info()
print("\n No FA - Hitters:")
df_hitters_no_free_agents[9].info()
print("\n No FA - Hitters:")
df_pitchers_no_free_agents[9].info()

FA - Hitters:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 38 entries, 0 to 37
Columns: 126 entries, Acronimo_t to ln_Sueldo_regular_t
dtypes: float64(40), int64(75), object(11)
memory usage: 37.7+ KB

 FA - Pitchers:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 0 to 45
Columns: 136 entries, Acronimo_t to ln_Sueldo_regular_t
dtypes: float64(44), int64(81), object(11)
memory usage: 49.2+ KB

 No FA - Hitters:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 243 entries, 0 to 280
Columns: 121 entries, Acronimo_t to ln_Sueldo_regular_t
dtypes: float64(40), int64(72), object(9)
memory usage: 231.6+ KB

 No FA - Hitters:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 309 entries, 0 to 353
Columns: 131 entries, Acronimo_t to ln_Sueldo_regular_t
dtypes: float64(44), int64(78), object(9)
memory usage: 318.7+ KB

In [107]:
print("FA - Hitters:")
for year in range(0,period):
    print(df_hitters_free_agents[year].shape)
print("\n FA - Pitchers:")
for year in range(0,period):
    print(df_pitchers_free_agents[year].shape)

FA - Hitters:
(0, 69)
(0, 126)
(116, 126)
(61, 126)
(63, 126)
(79, 126)
(45, 126)
(42, 126)
(48, 126)
(38, 126)
(29, 126)
(49, 126)

 FA - Pitchers:
(0, 74)
(2, 136)
(75, 136)
(49, 136)
(53, 136)
(63, 136)
(33, 136)
(44, 136)
(39, 136)
(46, 136)
(46, 136)
(92, 136)

Por último, para facilitar futuras aplicaciones, pasemos todos los nombres de las columnas a miníscula

In [108]:
for year in range(0,period):
    df_hitters_free_agents[year].rename(columns = str.lower)
    df_pitchers_free_agents[year].rename(columns = str.lower)
    df_hitters_no_free_agents[year].rename(columns = str.lower)
    df_pitchers_no_free_agents[year].rename(columns = str.lower)

In [115]:
start_year = 2011
end_year = 2022
general_trans_path = 'ETL_Data/Transversal/Yearly_average'

In [117]:
for year in range(0,period):    
    # Exportemos los dataframes por separado
    df_hitters_free_agents[year].to_csv(general_trans_path + '/Hitters/Free_Agent/hitters_' + str(start_year + year) + '.csv',
                                        index = False)
    df_pitchers_free_agents[year].to_csv(general_trans_path + '/Fielders/Free_Agent/fielders_' + str(start_year + year) + '.csv',
                                         index = False)
    df_hitters_no_free_agents[year].to_csv(general_trans_path + '/Hitters/No_Free_Agent/hitters_' + str(start_year + year) + '.csv',
                                           index = False)
    df_pitchers_no_free_agents[year].to_csv(general_trans_path + '/Fielders/No_Free_Agent/fielders_' + str(start_year + year) + '.csv',
                                            index = False)

### Etiquetas para los agentes libres

Crearemos un etiqueta para indicar si el pitcher o hitter es  un agente libre o no.

In [118]:
for year in range(0,period):
    # Condiciones
    condicion_hitter = [df_hitting_copy[year].Jugador.isin(df_free_agents_copy[year].Jugador)]
    condicion_pitcher = [df_pitching_copy[year].Jugador.isin(df_free_agents_copy[year].Jugador)]
    
    # Etiquetas
    etiquetas = ['Si']
    
    df_hitting_copy[year]['Agente_libre'] = np.select(condicion_hitter, etiquetas, default = 'No')
    df_pitching_copy[year]['Agente_libre'] = np.select(condicion_pitcher, etiquetas, default = 'No')
    
    df_hitting_copy[year] = df_hitting_copy[year].reindex(sorted(df_hitting_copy[year].columns), axis=1)
    df_pitching_copy[year] = df_pitching_copy[year].reindex(sorted(df_pitching_copy[year].columns), axis=1)

In [119]:
for year in range(0,period):
    df_hitting_copy[year].rename(columns = str.lower)
    df_pitching_copy[year].rename(columns = str.lower)

In [120]:
for year in range(0,period):
    # Exportemos los dataframes
    df_hitting_copy[year].to_csv(general_trans_path + '/Hitters/All/hitters_' + str(start_year + year) + '.csv',
                                        index = False)
    df_pitching_copy[year].to_csv(general_trans_path + '/Fielders/All/hitters_' + str(start_year + year) + '.csv',
                                        index = False)

## Panel Data

Con el objetivo de contar con una base de datos en estructura panel, uniremos las bases de datos

In [121]:
# Inicialización del panel
df_panel_all_hitter = df_hitting_copy[0]
df_panel_all_pitcher = df_pitching_copy[0]

for year in range(1,period):
    # Hitter
    df_panel_all_hitter = pd.concat([df_panel_all_hitter, df_hitting_copy[year]])
    
    # Pitcher
    df_panel_all_pitcher = pd.concat([df_panel_all_pitcher, df_pitching_copy[year]])

Veamos las estadísticas descriptivas de los panel

In [122]:
df_panel_all_hitter[['ln_Sueldo_ajustado_t']].describe()

       ln_Sueldo_ajustado_t
count           4595.000000
mean              14.233341
std                1.584724
min                8.620832
25%               13.123762
50%               14.045085
75%               15.607270
max               17.440000

In [123]:
df_panel_all_pitcher.describe()

,Altura_t,Anio_de_agente_libre_t,Anios_de_contrato_t,Antiguedad_t,Bateos_2_t,Bateos_t,Bono_por_firma_t,Cantidad de equipos_t,Cantidad_agentes_libres_t,Carreras_2_t,...,WAR_2_t_1,WAR_t_1,WHIP_2_t_1,WHIP_t_1,WS_ganadas_t,WS_ganadas_t_1,Walks_2_t_1,Walks_t_1,Wins_2_t_1,Wins_t_1
count,3897.000000,3897.000000,3897.000000,3897.000000,3897.000000,3897.000000,3.897000e+03,13.0,3897.000000,3897.000000,...,3884.000000,3884.000000,3884.000000,3884.000000,3884.000000,3884.000000,3884.000000,3884.000000,3884.000000,3884.000000
mean,6.264999,1041.235309,1.624583,0.805748,8721.861945,73.674622,1.055789e+05,1.0,5.581986,2196.781627,...,3.153834,1.344219,2.003434,1.325000,3.936921,4.006179,1019.339341,25.763131,40.715757,4.596292
std,0.206964,1009.945283,1.349554,1.054709,11754.391428,57.399979,5.972387e+05,0.0,3.057124,2944.651190,...,6.621021,1.160714,7.309909,0.497868,5.382786,5.545909,1367.674363,18.859799,68.333585,4.426612
min,5.567014,0.000000,1.000000,-1.000000,0.000000,0.000000,0.000000e+00,1.0,1.000000,0.000000,...,0.000100,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.100000,0.000000,1.000000,0.000000,1024.000000,32.000000,0.000000e+00,1.0,3.000000,256.000000,...,0.348100,0.590000,1.299600,1.140000,1.000000,1.000000,121.000000,11.000000,1.000000,1.000000
50%,6.300000,2014.000000,1.000000,1.000000,2809.000000,53.000000,0.000000e+00,1.0,5.000000,729.000000,...,1.439542,1.199809,1.638400,1.280000,2.000000,2.000000,441.000000,21.000000,9.000000,3.000000
75%,6.400000,2021.000000,1.000000,1.000000,13225.000000,115.000000,0.000000e+00,1.0,8.000000,3249.000000,...,2.220100,1.490000,2.073600,1.440000,5.000000,5.000000,1369.000000,37.000000,49.000000,7.000000
max,6.900000,2029.000000,9.000000,8.000000,57600.000000,240.000000,1.000000e+07,1.0,18.000000,15625.000000,...,93.896100,9.690000,441.000000,21.000000,27.000000,27.000000,11025.000000,105.000000,484.000000,22.000000

In [124]:
df_panel_all_hitter.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4595 entries, 0 to 295
Columns: 136 entries, Acronimo_t to WS_ganadas_t_1
dtypes: float64(100), int64(26), object(10)
memory usage: 4.8+ MB

In [125]:
df_panel_all_pitcher.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3897 entries, 0 to 395
Columns: 138 entries, Acronimo_t to Wins_t_1
dtypes: float64(95), int64(33), object(10)
memory usage: 4.1+ MB

Verifquemos que no haya problemas con valores *NaN* o *infinitos*

Valores *NaN*:

In [126]:
"""for name in df_panel_all_hitter.columns:
    print(name)
    if type(name) != str:
        for element in range(0,len(df_panel_all_hitter[name])):
            if pd.isna(df_panel_all_hitter[name].iloc[element]) == True:
                print(str(element) +  '  ' + str(df_panel_all_hitter[name].iloc[element]))"""

"for name in df_panel_all_hitter.columns:\n    print(name)\n    if type(name) != str:\n        for element in range(0,len(df_panel_all_hitter[name])):\n            if pd.isna(df_panel_all_hitter[name].iloc[element]) == True:\n                print(str(element) +  '  ' + str(df_panel_all_hitter[name].iloc[element]))"

In [127]:
"""for name in df_panel_all_pitcher.columns:
    print(name)
    if type(name) != str:
        for element in range(0,len(df_panel_all_pitcher[name])):
            if pd.isna(df_panel_all_pitcher[name].iloc[element]) == True:
                print(str(element) +  '  ' + str(df_panel_all_pitcher[name].iloc[element]))"""

"for name in df_panel_all_pitcher.columns:\n    print(name)\n    if type(name) != str:\n        for element in range(0,len(df_panel_all_pitcher[name])):\n            if pd.isna(df_panel_all_pitcher[name].iloc[element]) == True:\n                print(str(element) +  '  ' + str(df_panel_all_pitcher[name].iloc[element]))"

Valores *infinitos*

In [128]:
for name in df_panel_all_hitter.columns:
    print(name)
    if type(name) != str:
        for element in range(0,len(df_panel_all_hitter[name])):
            if math.isinf(df_panel_all_hitter[name].iloc[element]) == True:
                print(str(element) +  '  ' + str(df_panel_all_hitter[name].iloc[element]))

Acronimo_t
Agente_libre
Altura_t
Anio_de_agente_libre_t
Anio_t
Anios_de_contrato_t
Antiguedad_t
At-bats_2_t
At-bats_t
Bateos_2_t
Bateos_promedio_2_t
Bateos_promedio_t
Bateos_t
Bono_por_firma_t
Cantidad de equipos_t
Cantidad_agentes_libres_t
Dobles_2_t
Dobles_t
Edad_al_firmar_t
Edad_t
Equipo_t
Estado_t
Ganancias_t
Home-runs_2_t
Home-runs_t
Juegos totales_t
Juegos_iniciados_2_t
Juegos_iniciados_t
Juegos_t
Jugador
Pago_efectivo_t
Pennants won_t
Peso_t
Playoffs_t
Porcentaje_On-base-plus-slugging_2_t
Porcentaje_On-base-plus-slugging_t
Porcentaje_juegos_iniciados_2_t
Porcentaje_juegos_iniciados_t
Porcentaje_juegos_t
Porcentaje_on-base_2_t
Porcentaje_on-base_t
Porcentaje_slugging_2_t
Porcentaje_slugging_t
Posicion_t
Promedio_victorias_t
Runs-batted-in_2_t
Runs-batted-in_t
Sueldo_ajustado_t
Sueldo_base_t
Sueldo_porcentual_t
Sueldo_regular_t
TVS_2_t
TVS_t
Triples_2_t
Triples_t
Valor_contrato_promedio_t
Valor_contrato_total_t
Valor_del_contrato_t
Victorias_t
WAR_2_t
WAR_t
WS ganadas_t
ln_Sueldo_ajustado_t
ln_Sueldo_base_t
ln_Sueldo_regular_t
Acronimo_t_1
Altura_t_1
Anio_de_agente_libre_t_1
Anios_de_contrato_t_1
Antiguedad_t_1
At_bats_2_t
At_bats_2_t_1
At_bats_t
At_bats_t_1
Bateos_2_t_1
Bateos_promedio_2_t_1
Bateos_promedio_t_1
Bateos_t_1
Bono_por_firma_t_1
Cantidad_agentes_libres_t_1
Cantidad_de_equipos_t
Cantidad_de_equipos_t_1
Dobles_2_t_1
Dobles_t_1
Edad_al_firmar_t_1
Equipo_t_1
Ganancias_t_1
Home_runs_2_t
Home_runs_2_t_1
Home_runs_t
Home_runs_t_1
Juegos_iniciados_2_t_1
Juegos_iniciados_t_1
Juegos_t_1
Juegos_totales_t
Juegos_totales_t_1
Pago_efectivo_t_1
Pennants_won_t
Pennants_won_t_1
Peso_t_1
Playoffs_t_1
Porcentaje_On_base_plus_slugging_2_t
Porcentaje_On_base_plus_slugging_2_t_1
Porcentaje_On_base_plus_slugging_t
Porcentaje_On_base_plus_slugging_t_1
Porcentaje_juegos_iniciados_2_t_1
Porcentaje_juegos_iniciados_t_1
Porcentaje_juegos_t_1
Porcentaje_on_base_2_t
Porcentaje_on_base_2_t_1
Porcentaje_on_base_t
Porcentaje_on_base_t_1
Porcentaje_slugging_2_t_1
Porcentaje_slugging_t_1
Posicion_t_1
Promedio_victorias_t_1
Runs_batted_in_2_t
Runs_batted_in_2_t_1
Runs_batted_in_t
Runs_batted_in_t_1
Sueldo_ajustado_t_1
Sueldo_base_t_1
Sueldo_porcentual_t_1
Sueldo_regular_t_1
TVS_2_t_1
TVS_t_1
Triples_2_t_1
Triples_t_1
Valor_contrato_promedio_t_1
Valor_contrato_total_t_1
Valor_del_contrato_t_1
Victorias_t_1
WAR_2_t_1
WAR_t_1
WS_ganadas_t
WS_ganadas_t_1

In [129]:
for name in df_panel_all_pitcher.columns:
    print(name)
    if type(name) != str:
        for element in range(0,len(df_panel_all_pitcher[name])):
            if math.isinf(df_panel_all_pitcher[name].iloc[element]) == True:
                print(str(element) +  '  ' + str(df_panel_all_pitcher[name].iloc[element]))

Acronimo_t
Agente_libre
Altura_t
Anio_de_agente_libre_t
Anio_t
Anios_de_contrato_t
Antiguedad_t
Bateos_2_t
Bateos_t
Bono_por_firma_t
Cantidad de equipos_t
Cantidad_agentes_libres_t
Carreras_2_t
Carreras_ganadas_2_t
Carreras_ganadas_t
Carreras_t
Comando_2_t
Comando_t
Control_2_t
Control_t
Dominio_2_t
Dominio_t
ERA_2_t
ERA_t
Edad_al_firmar_t
Edad_t
Equipo_t
Estado_t
Ganancias_t
Inning_pitched_2_t
Inning_pitched_t
Juegos totales_t
Juegos_iniciados_t
Juegos_t
Jugador
Losses_2_t
Losses_t
Pago_efectivo_t
Pennants won_t
Peso_t
Playoffs_t
Porcentaje_juegos_t
Posicion_t
Promedio_victorias_t
Saves_2_t
Saves_t
Strike-outs_2_t
Strike-outs_t
Sueldo_ajustado_t
Sueldo_base_t
Sueldo_porcentual_t
Sueldo_regular_t
TVS_2_t
TVS_t
Valor_contrato_promedio_t
Valor_contrato_total_t
Valor_del_contrato_t
Victorias_t
WAR_2_t
WAR_t
WHIP_2_t
WHIP_t
WS ganadas_t
Walks_2_t
Walks_t
Wins_2_t
Wins_t
ln_Sueldo_ajustado_t
ln_Sueldo_base_t
ln_Sueldo_regular_t
Acronimo_t_1
Altura_t_1
Anio_de_agente_libre_t_1
Anios_de_contrato_t_1
Antiguedad_t_1
Bateos_2_t_1
Bateos_t_1
Bono_por_firma_t_1
Cantidad_agentes_libres_t_1
Cantidad_de_equipos_t
Cantidad_de_equipos_t_1
Carreras_2_t_1
Carreras_ganadas_2_t_1
Carreras_ganadas_t_1
Carreras_t_1
Comando_2_t_1
Comando_t_1
Control_2_t_1
Control_t_1
Dominio_2_t_1
Dominio_t_1
ERA_2_t_1
ERA_t_1
Edad_al_firmar_t_1
Equipo_t_1
Ganancias_t_1
Inning_pitched_2_t_1
Inning_pitched_t_1
Juegos_iniciados_t_1
Juegos_t_1
Juegos_totales_t
Juegos_totales_t_1
Losses_2_t_1
Losses_t_1
Pago_efectivo_t_1
Pennants_won_t
Pennants_won_t_1
Peso_t_1
Playoffs_t_1
Porcentaje_juegos_t_1
Posicion_t_1
Promedio_victorias_t_1
Saves_2_t_1
Saves_t_1
Strike_outs_2_t
Strike_outs_2_t_1
Strike_outs_t
Strike_outs_t_1
Sueldo_ajustado_t_1
Sueldo_base_t_1
Sueldo_porcentual_t_1
Sueldo_regular_t_1
TVS_2_t_1
TVS_t_1
Valor_contrato_promedio_t_1
Valor_contrato_total_t_1
Valor_del_contrato_t_1
Victorias_t_1
WAR_2_t_1
WAR_t_1
WHIP_2_t_1
WHIP_t_1
WS_ganadas_t
WS_ganadas_t_1
Walks_2_t_1
Walks_t_1
Wins_2_t_1
Wins_t_1

In [130]:
df_panel_all_hitter.sort_index(axis = 1,
                               inplace = True)
df_panel_all_pitcher.sort_index(axis = 1,
                                inplace = True)

Repetiremos el procedimiento, pero únicamente para quienes son agentes libres

In [131]:
# Inicialización del panel
df_panel_fa_hitter = df_hitters_free_agents[0]
df_panel_fa_pitcher = df_pitchers_free_agents[0]

for year in range(1,period):
    # Hitter
    df_panel_fa_hitter = pd.concat([df_panel_fa_hitter, df_hitters_free_agents[year]])
    
    # Pitcher
    df_panel_fa_pitcher = pd.concat([df_panel_fa_pitcher, df_pitchers_free_agents[year]])

In [132]:
df_panel_fa_hitter.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 570 entries, 0 to 48
Columns: 140 entries, Acronimo_t to WS_ganadas_t_1
dtypes: float64(100), int64(29), object(11)
memory usage: 627.9+ KB

In [133]:
df_panel_fa_pitcher.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 542 entries, 0 to 91
Columns: 142 entries, Acronimo_t to Wins_t_1
dtypes: float64(95), int64(36), object(11)
memory usage: 605.5+ KB

In [134]:
df_panel_fa_hitter.drop('Anios_de_contrato',
                        axis = 1, inplace = True)
df_panel_fa_pitcher.drop('Anios_de_contrato',
                         axis = 1, inplace = True)

In [135]:
df_panel_fa_hitter.sort_index(axis = 1, inplace = True)
df_panel_fa_pitcher.sort_index(axis = 1, inplace = True)

# Variables del Modelo Empírico

In [136]:
empiric_panel_hitter = df_panel_fa_hitter.copy()
empiric_panel_pitcher = df_panel_fa_pitcher.copy()

Veamos algunas estadísticas e información que contienen las bases de datos

In [137]:
print(empiric_panel_hitter.shape)

(570, 139)

In [138]:
print(empiric_panel_pitcher.shape)

(542, 141)

Las posiciones que hay en cada base de datos

In [139]:
empiric_panel_hitter['Posicion_t'].unique()

array(['SP', 'LF', 'RP', 'RF', 'DH', '2B', 'C', '1B', '3B', 'CF', 'SS',
       'OF'], dtype=object)

In [140]:
empiric_panel_pitcher['Posicion_t'].unique()

array(['RP/CL', 'SP', 'RP', 'RF', 'SS'], dtype=object)

Ordenemos las bases de datos  por nombre y año

In [141]:
# Hitter
empiric_panel_hitter = empiric_panel_hitter.sort_values(by = ['Jugador','Anio_t'], ascending=True)
empiric_panel_hitter.reset_index(drop = True, inplace = True)

# Pitcher
empiric_panel_pitcher = empiric_panel_pitcher.sort_values(by = ['Jugador','Anio_t'], ascending=True)
empiric_panel_pitcher.reset_index(drop = True, inplace = True)

In [142]:
empiric_panel_hitter[['Jugador','Anio_t']].head()

           Jugador Anio_t
0     A.J. Burnett   2014
1     A.J. Burnett   2015
2       A.J. Ellis   2017
3  A.J. Pierzynski   2013
4  A.J. Pierzynski   2013

In [143]:
empiric_panel_pitcher[['Jugador','Anio_t']].head()

         Jugador Anio_t
0   A.J. Burnett   2014
1   A.J. Burnett   2015
2   Aaron Harang   2015
3  Adam Ottavino   2019
4  Adam Ottavino   2022

In [144]:
"""hitter_names = empiric_panel_hitter.columns
for index in range(0,len(hitter_names)):
    print("Name: " + str(hitter_names[index]))
    print("index: " + str(index))"""

'hitter_names = empiric_panel_hitter.columns\nfor index in range(0,len(hitter_names)):\n    print("Name: " + str(hitter_names[index]))\n    print("index: " + str(index))'

Obtengamos los índices de las columnas de interes

In [145]:
hitter_regular_stats = ['At_bats_2_t_1', 'At_bats_t_1',
                        'Bateos_2_t_1', 'Bateos_t_1',
                        'Bateos_promedio_2_t_1', 'Bateos_promedio_t_1',
                        'Dobles_2_t_1', 'Dobles_t_1',
                        'Home_runs_2_t_1', 'Home_runs_t_1',
                        'Juegos_iniciados_2_t_1', 'Juegos_iniciados_t_1', 
                        'Porcentaje_On_base_plus_slugging_2_t_1', 'Porcentaje_On_base_plus_slugging_t_1',
                        'Porcentaje_on_base_2_t_1', 'Porcentaje_on_base_t_1',
                        'Porcentaje_slugging_2_t_1', 'Porcentaje_slugging_t_1',
                        'Runs_batted_in_2_t_1', 'Runs_batted_in_t_1',
                        'Triples_2_t_1', 'Triples_t_1',
                        'WAR_2_t_1', 'WAR_t_1']
hitter_regular_stats = sorted(hitter_regular_stats)

In [146]:
# Hitter
for stat in range(0,len(hitter_regular_stats)):
    # Variables auxiliares
    stat_name = hitter_regular_stats[stat]
    max_stat_name = stat_name + '_H'
    min_stat_name = stat_name + '_L'
    
    # Máximos por equipo
    max_stat = pd.DataFrame({"Acronimo_t":empiric_panel_hitter.groupby(by = "Acronimo_t")[stat_name].max().index,
                             max_stat_name: empiric_panel_hitter.groupby(by = "Acronimo_t")[stat_name].max().values})
    # Mínimos por equipo
    min_stat = pd.DataFrame({"Acronimo_t":empiric_panel_hitter.groupby(by = "Acronimo_t")[stat_name].min().index,
                             min_stat_name: empiric_panel_hitter.groupby(by = "Acronimo_t")[stat_name].min().values})
    empiric_panel_hitter = empiric_panel_hitter.merge(max_stat, on = "Acronimo_t",
                                                      how = "left")
    empiric_panel_hitter = empiric_panel_hitter.merge(min_stat, on = "Acronimo_t",
                                                      how = "left")

In [147]:
"""hitter_names = empiric_panel_hitter.columns
for index in range(0,len(hitter_names)):
    print("Name: " + str(hitter_names[index]))
    print("index: " + str(index))"""

'hitter_names = empiric_panel_hitter.columns\nfor index in range(0,len(hitter_names)):\n    print("Name: " + str(hitter_names[index]))\n    print("index: " + str(index))'

In [148]:
start = empiric_panel_hitter.columns.get_loc('At_bats_2_t_1_H')
end = empiric_panel_hitter.columns.get_loc('WAR_t_1_L') + 1
empiric_panel_hitter.iloc[:,start:end]

,At_bats_2_t_1_H,At_bats_2_t_1_L,At_bats_t_1_H,At_bats_t_1_L,Bateos_2_t_1_H,Bateos_2_t_1_L,Bateos_promedio_2_t_1_H,Bateos_promedio_2_t_1_L,Bateos_promedio_t_1_H,Bateos_promedio_t_1_L,...,Runs_batted_in_t_1_H,Runs_batted_in_t_1_L,Triples_2_t_1_H,Triples_2_t_1_L,Triples_t_1_H,Triples_t_1_L,WAR_2_t_1_H,WAR_2_t_1_L,WAR_t_1_H,WAR_t_1_L
0,344569.0,1.0,587.0,1.0,26896.0,1.0,1.000000,0.004624,1.000,0.068,...,100.0,0.0,25.0,0.0,5.0,0.0,14.8996,0.1156,3.86,0.34
1,191844.0,1.0,438.0,1.0,14884.0,0.0,0.082369,0.000000,0.287,0.000,...,61.0,0.0,9.0,0.0,3.0,0.0,8.1225,0.0025,2.85,0.05
2,379456.0,16.0,616.0,4.0,31329.0,0.0,0.092416,0.000000,0.304,0.000,...,86.0,0.0,4.0,0.0,2.0,0.0,8.4100,0.0961,2.90,0.31
3,425104.0,1.0,652.0,1.0,29929.0,0.0,0.250000,0.000000,0.500,0.000,...,102.0,0.0,16.0,0.0,4.0,0.0,52.5625,0.0144,7.25,0.12
4,425104.0,1.0,652.0,1.0,29929.0,0.0,0.250000,0.000000,0.500,0.000,...,102.0,0.0,16.0,0.0,4.0,0.0,52.5625,0.0144,7.25,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,341056.0,4.0,584.0,2.0,31329.0,0.0,1.000000,0.000000,1.000,0.000,...,95.0,0.0,25.0,0.0,5.0,0.0,30.2500,0.1225,5.50,0.35
566,315844.0,64.0,562.0,8.0,25600.0,1.0,0.087025,0.005329,0.295,0.073,...,127.0,0.0,49.0,0.0,7.0,0.0,26.9361,0.0121,5.19,0.11
567,360000.0,16.0,600.0,4.0,32400.0,0.0,0.090000,0.000000,0.300,0.000,...,83.0,0.0,25.0,0.0,5.0,0.0,21.6225,0.0001,4.65,0.01
568,360000.0,16.0,600.0,4.0,32400.0,0.0,0.090000,0.000000,0.300,0.000,...,83.0,0.0,25.0,0.0,5.0,0.0,21.6225,0.0001,4.65,0.01
569,336400.0,4.0,580.0,2.0,26569.0,0.0,0.078961,0.000000,0.281,0.000,...,63.0,0.0,9.0,0.0,3.0,0.0,78.8544,0.0400,8.88,0.20

Repitamos el mismo proceso para los lanzadores

In [149]:
"""pitcher_names = empiric_panel_pitcher.columns
for index in range(0,len(pitcher_names)):
    print("Name: " + str(pitcher_names[index]))
    print("index: " + str(index))"""

'pitcher_names = empiric_panel_pitcher.columns\nfor index in range(0,len(pitcher_names)):\n    print("Name: " + str(pitcher_names[index]))\n    print("index: " + str(index))'

Repitamos el mismo proceso para los filderos

In [150]:
pitcher_regular_stats = ['Bateos_2_t_1', 'Bateos_t_1',
                        'Carreras_2_t_1', 'Carreras_t_1',
                        'Carreras_ganadas_2_t_1', 'Carreras_ganadas_t_1',
                        'Comando_2_t_1', 'Comando_t_1',
                        'Control_2_t_1', 'Control_t_1',
                        'Dominio_2_t_1', 'Dominio_t_1', 
                        'ERA_2_t_1', 'ERA_t_1',
                        'Inning_pitched_2_t_1', 'Inning_pitched_t_1',
                        'Losses_2_t_1', 'Losses_t_1',
                        'Saves_2_t_1', 'Saves_t_1',
                        'Strike_outs_2_t_1', 'Strike_outs_t_1',
                        'WAR_2_t_1', 'WAR_t_1',
                        'WHIP_2_t_1', 'WHIP_t_1',
                        'Walks_2_t_1', 'Walks_t_1',
                        'Wins_2_t_1', 'Wins_t_1']
pitcher_regular_stats = sorted(pitcher_regular_stats)

In [151]:
# Pitcheer
for stat in range(0,len(pitcher_regular_stats)):
    # Variables auxiliares
    stat_name = pitcher_regular_stats[stat]
    max_stat_name = stat_name + '_H'
    min_stat_name = stat_name + '_L'
    
    # Máximos por equipo
    max_stat = pd.DataFrame({"Acronimo_t":empiric_panel_pitcher.groupby(by = "Acronimo_t")[stat_name].max().index,
                             max_stat_name: empiric_panel_pitcher.groupby(by = "Acronimo_t")[stat_name].max().values})
    # Mínimos por equipo
    min_stat = pd.DataFrame({"Acronimo_t":empiric_panel_pitcher.groupby(by = "Acronimo_t")[stat_name].min().index,
                             min_stat_name: empiric_panel_pitcher.groupby(by = "Acronimo_t")[stat_name].min().values})
    empiric_panel_pitcher = empiric_panel_pitcher.merge(max_stat, on = "Acronimo_t",
                                                        how = "left")
    empiric_panel_pitcher = empiric_panel_pitcher.merge(min_stat, on = "Acronimo_t",
                                                        how = "left")

In [152]:
"""pitcher_names = empiric_panel_pitcher.columns
for index in range(0,len(pitcher_names)):
    print("Name: " + str(pitcher_names[index]))
    print("index: " + str(index))"""

'pitcher_names = empiric_panel_pitcher.columns\nfor index in range(0,len(pitcher_names)):\n    print("Name: " + str(pitcher_names[index]))\n    print("index: " + str(index))'

In [153]:
start = empiric_panel_pitcher.columns.get_loc('Bateos_2_t_1_H')
end = empiric_panel_pitcher.columns.get_loc('Wins_t_1_L') + 1
empiric_panel_pitcher.iloc[:,start:end]

,Bateos_2_t_1_H,Bateos_2_t_1_L,Bateos_t_1_H,Bateos_t_1_L,Carreras_2_t_1_H,Carreras_2_t_1_L,Carreras_ganadas_2_t_1_H,Carreras_ganadas_2_t_1_L,Carreras_ganadas_t_1_H,Carreras_ganadas_t_1_L,...,WHIP_t_1_H,WHIP_t_1_L,Walks_2_t_1_H,Walks_2_t_1_L,Walks_t_1_H,Walks_t_1_L,Wins_2_t_1_H,Wins_2_t_1_L,Wins_t_1_H,Wins_t_1_L
0,46225.0,4.0,215.0,2.0,8649.0,0.0,7396.0,0.0,86.0,0.0,...,1.50,0.38,5041.0,0.0,71.0,0.0,196.0,0.0,14.0,0.0
1,42025.0,256.0,205.0,16.0,14884.0,100.0,11881.0,81.0,109.0,9.0,...,1.59,1.14,9216.0,196.0,96.0,14.0,144.0,1.0,12.0,1.0
2,46225.0,4.0,215.0,2.0,8649.0,0.0,7396.0,0.0,86.0,0.0,...,1.50,0.38,5041.0,0.0,71.0,0.0,196.0,0.0,14.0,0.0
3,42025.0,0.0,205.0,0.0,7396.0,0.0,6561.0,0.0,81.0,0.0,...,1.39,0.80,6084.0,1.0,78.0,1.0,400.0,0.0,20.0,0.0
4,39204.0,0.0,198.0,0.0,12996.0,0.0,11449.0,0.0,107.0,0.0,...,1.62,0.00,3364.0,0.0,58.0,0.0,324.0,0.0,18.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,49284.0,1.0,222.0,1.0,10000.0,0.0,8100.0,0.0,90.0,0.0,...,3.00,0.65,3481.0,4.0,59.0,2.0,225.0,0.0,15.0,0.0
538,49284.0,1.0,222.0,1.0,10000.0,0.0,8100.0,0.0,90.0,0.0,...,3.00,0.65,3481.0,4.0,59.0,2.0,225.0,0.0,15.0,0.0
539,39601.0,49.0,199.0,7.0,9801.0,36.0,9025.0,36.0,95.0,6.0,...,2.73,0.85,5625.0,9.0,75.0,3.0,361.0,0.0,19.0,0.0
540,42436.0,49.0,206.0,7.0,11881.0,49.0,9216.0,49.0,96.0,7.0,...,2.79,1.09,5041.0,36.0,71.0,6.0,225.0,0.0,15.0,0.0
541,46225.0,4.0,215.0,2.0,8649.0,0.0,7396.0,0.0,86.0,0.0,...,1.50,0.38,5041.0,0.0,71.0,0.0,196.0,0.0,14.0,0.0

In [154]:
empiric_panel_hitter.shape

(570, 187)

In [155]:
empiric_panel_pitcher.shape

(542, 201)

### Filtrando jugadores con más de dos años de observaciones en nuestro panel

In [156]:
# Hitters:
# count number of observations for each player
counts_hitters = empiric_panel_hitter.groupby('Jugador').size()
# filter players with more than one year of observations
filtered_hitters = counts_hitters[counts_hitters > 2].index.tolist()

# Fielders:
# count number of observations for each player
counts_filders = empiric_panel_pitcher.groupby('Jugador').size()
# filter players with more than one year of observations
filtered_fielders = counts_filders[counts_filders > 2].index.tolist()

In [157]:
# Filter observations according to the previous list
# Hitter
empiric_panel_hitter = empiric_panel_hitter[empiric_panel_hitter['Jugador'].isin(filtered_hitters)]
empiric_panel_hitter.reset_index(drop = True,
                                 inplace = True)

# Pitcher
empiric_panel_pitcher = empiric_panel_pitcher[empiric_panel_pitcher['Jugador'].isin(filtered_fielders)]
empiric_panel_pitcher.reset_index(drop = True,
                                  inplace = True)

In [158]:
empiric_panel_hitter

,Acronimo_t,Acronimo_t_1,Altura_t,Altura_t_1,Anio_de_agente_libre_t,Anio_de_agente_libre_t_1,Anio_t,Anios_de_contrato_t,Anios_de_contrato_t_1,Antiguedad_t,...,Runs_batted_in_t_1_H,Runs_batted_in_t_1_L,Triples_2_t_1_H,Triples_2_t_1_L,Triples_t_1_H,Triples_t_1_L,WAR_2_t_1_H,WAR_2_t_1_L,WAR_t_1_H,WAR_t_1_L
0,TEX,CHW,6.3,6.3,0,0.0,2013,1,2.0,0,...,102.0,0.0,16.0,0.0,4.0,0.0,52.5625,0.0144,7.25,0.12
1,TEX,CHW,6.3,6.3,0,0.0,2013,1,2.0,0,...,102.0,0.0,16.0,0.0,4.0,0.0,52.5625,0.0144,7.25,0.12
2,STL,TEX,6.3,6.3,0,0.0,2014,1,1.0,0,...,70.0,0.0,49.0,0.0,7.0,0.0,15.9201,0.0169,3.99,0.13
3,ATL,STL,6.3,6.3,0,0.0,2015,1,1.0,0,...,93.0,0.0,81.0,0.0,9.0,0.0,10.3041,0.0900,3.21,0.30
4,ATL,ATL,6.3,6.3,0,0.0,2016,1,1.0,0,...,93.0,0.0,81.0,0.0,9.0,0.0,10.3041,0.0900,3.21,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,CIN,WSH,6.2,6.2,0,2013.0,2013,1,1.0,1,...,87.0,0.0,9.0,0.0,3.0,0.0,6.7600,0.0256,2.60,0.16
192,MIL,CIN,6.2,6.2,2015,0.0,2014,1,1.0,1,...,95.0,0.0,25.0,0.0,5.0,0.0,30.2500,0.1225,5.50,0.35
193,LAD,MIL,6.2,6.2,2016,2013.0,2013,6,4.0,0,...,83.0,0.0,25.0,0.0,5.0,0.0,21.6225,0.0001,4.65,0.01
194,LAD,MIL,6.2,6.2,2016,2013.0,2013,6,4.0,0,...,83.0,0.0,25.0,0.0,5.0,0.0,21.6225,0.0001,4.65,0.01
195,ARI,LAD,6.2,6.2,2022,2016.0,2016,6,6.0,0,...,63.0,0.0,9.0,0.0,3.0,0.0,78.8544,0.0400,8.88,0.20

In [159]:
empiric_panel_pitcher

,Acronimo_t,Acronimo_t_1,Altura_t,Altura_t_1,Anio_de_agente_libre_t,Anio_de_agente_libre_t_1,Anio_t,Anios_de_contrato_t,Anios_de_contrato_t_1,Antiguedad_t,...,WHIP_t_1_H,WHIP_t_1_L,Walks_2_t_1_H,Walks_2_t_1_L,Walks_t_1_H,Walks_t_1_L,Wins_2_t_1_H,Wins_2_t_1_L,Wins_t_1_H,Wins_t_1_L
0,LAD,CIN,6.4,6.4,0,0.0,2020,1,1.0,1,...,3.00,0.65,3481.0,4.0,59.0,2.0,225.0,0.0,15.0,0.0
1,SF,LAD,6.4,6.4,0,0.0,2021,1,1.0,1,...,1.82,0.00,3969.0,0.0,63.0,0.0,169.0,0.0,13.0,0.0
2,SF,SF,6.4,6.4,2024,0.0,2022,2,1.0,1,...,1.82,0.00,3969.0,0.0,63.0,0.0,169.0,0.0,13.0,0.0
3,DET,DET,6.0,6.0,2018,2013.0,2013,5,1.0,1,...,1.74,0.90,3844.0,64.0,62.0,8.0,169.0,0.0,13.0,0.0
4,ATL,DET,6.0,6.0,2019,2018.0,2018,1,5.0,1,...,2.17,0.75,3969.0,1.0,63.0,1.0,144.0,0.0,12.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,CHW,MIL,6.2,6.2,2018,2015.0,2015,3,1.0,1,...,2.70,0.67,3025.0,0.0,55.0,0.0,81.0,0.0,9.0,0.0
215,LAD,MIL,6.2,6.2,2016,2013.0,2013,6,4.0,0,...,3.00,0.65,3481.0,4.0,59.0,2.0,225.0,0.0,15.0,0.0
216,LAD,MIL,6.2,6.2,2016,2013.0,2013,6,4.0,0,...,3.00,0.65,3481.0,4.0,59.0,2.0,225.0,0.0,15.0,0.0
217,ARI,LAD,6.2,6.2,2022,2016.0,2016,6,6.0,0,...,2.73,0.85,5625.0,9.0,75.0,3.0,361.0,0.0,19.0,0.0
218,KC,HOU,6.2,6.2,2023,2022.0,2022,1,6.0,0,...,2.79,1.09,5041.0,36.0,71.0,6.0,225.0,0.0,15.0,0.0

Para ser consistentes, las columnas que contienen datos de tipo *string* las imputaremos con la palabra *No* ya que representará que no tenía equipo, ni posición, etc.

In [160]:
empiric_panel_hitter.select_dtypes(include =['object'],
                                   exclude = ['int64','float64']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Acronimo_t           196 non-null    object
 1   Acronimo_t_1         196 non-null    object
 2   Anio_t               196 non-null    object
 3   Equipo_anterior      196 non-null    object
 4   Equipo_t             196 non-null    object
 5   Equipo_t_1           196 non-null    object
 6   Estado_t             196 non-null    object
 7   Jugador              196 non-null    object
 8   Posicion_t           196 non-null    object
 9   Posicion_t_1         196 non-null    object
 10  Status_agente_libre  196 non-null    object
dtypes: object(11)
memory usage: 17.0+ KB

In [161]:
empiric_panel_hitter[['Acronimo_t',
                      'Equipo_anterior',
                      'Equipo_t',
                      'Estado_t',
                      'Posicion_t',
                      'Status_agente_libre',
                      'Acronimo_t_1',
                      'Equipo_t_1',
                      'Posicion_t_1']] = \
empiric_panel_hitter[['Acronimo_t',
                      'Equipo_anterior',
                      'Equipo_t',
                      'Estado_t',
                      'Posicion_t',
                      'Status_agente_libre',
                      'Acronimo_t_1',
                      'Equipo_t_1',
                      'Posicion_t_1']].fillna('No')

Veamos si funcionó la imputación

In [162]:
empiric_panel_hitter.select_dtypes(include =['object'],
                                   exclude = ['int64','float64']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Acronimo_t           196 non-null    object
 1   Acronimo_t_1         196 non-null    object
 2   Anio_t               196 non-null    object
 3   Equipo_anterior      196 non-null    object
 4   Equipo_t             196 non-null    object
 5   Equipo_t_1           196 non-null    object
 6   Estado_t             196 non-null    object
 7   Jugador              196 non-null    object
 8   Posicion_t           196 non-null    object
 9   Posicion_t_1         196 non-null    object
 10  Status_agente_libre  196 non-null    object
dtypes: object(11)
memory usage: 17.0+ KB

Ahora con los lanzadores

In [163]:
empiric_panel_pitcher.select_dtypes(include =['object'],
                                    exclude = ['int64','float64']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Acronimo_t           219 non-null    object
 1   Acronimo_t_1         219 non-null    object
 2   Anio_t               219 non-null    object
 3   Equipo_anterior      219 non-null    object
 4   Equipo_t             219 non-null    object
 5   Equipo_t_1           219 non-null    object
 6   Estado_t             219 non-null    object
 7   Jugador              219 non-null    object
 8   Posicion_t           219 non-null    object
 9   Posicion_t_1         219 non-null    object
 10  Status_agente_libre  219 non-null    object
dtypes: object(11)
memory usage: 18.9+ KB

In [164]:
empiric_panel_pitcher[['Acronimo_t',
                       'Equipo_anterior',
                       'Equipo_t',
                       'Estado_t',
                       'Posicion_t',
                       'Status_agente_libre',
                       'Acronimo_t_1',
                       'Equipo_t_1',
                       'Posicion_t_1']] = \
empiric_panel_pitcher[['Acronimo_t',
                       'Equipo_anterior',
                       'Equipo_t',
                       'Estado_t',
                       'Posicion_t',
                       'Status_agente_libre',
                       'Acronimo_t_1',
                       'Equipo_t_1',
                       'Posicion_t_1']].fillna('No')

In [165]:
empiric_panel_pitcher.select_dtypes(include =['object'],
                                    exclude = ['int64','float64']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Acronimo_t           219 non-null    object
 1   Acronimo_t_1         219 non-null    object
 2   Anio_t               219 non-null    object
 3   Equipo_anterior      219 non-null    object
 4   Equipo_t             219 non-null    object
 5   Equipo_t_1           219 non-null    object
 6   Estado_t             219 non-null    object
 7   Jugador              219 non-null    object
 8   Posicion_t           219 non-null    object
 9   Posicion_t_1         219 non-null    object
 10  Status_agente_libre  219 non-null    object
dtypes: object(11)
memory usage: 18.9+ KB

En ambos casos, la imputación fue un éxito. No importa que en periodos de contratación de haya puesto *No* ya que con esto evitamos problemas con posibles instrumentos a partir de dummies.

Por otro lado, repitamos lo mismo para las columnas numéricas, imputaremos 0 ya que refleja la ausencia de desempeño. Sin embargo, la columna que contiene la estadística más alta de cada medida de desempeño se imputará por separado debido a que causará problemas cuando se imponga la trnasformación para el modelo.

In [166]:
# Add string to every element in a list
# Hitter
hitter_high_stat = [stat + '_H' for stat in hitter_regular_stats]
hitter_low_stat = [stat + '_L' for stat in hitter_regular_stats]
# Fielder
pitcher_high_stat = [stat + '_H' for stat in pitcher_regular_stats]
pitcher_low_stat = [stat + '_L' for stat in pitcher_regular_stats]

In [167]:
empiric_panel_hitter[hitter_high_stat] = empiric_panel_hitter[hitter_high_stat].fillna(method = 'ffill')
empiric_panel_pitcher[pitcher_high_stat] = empiric_panel_pitcher[pitcher_high_stat].fillna(method = 'ffill')

In [168]:
empiric_panel_hitter[hitter_high_stat].head(20)

,At_bats_2_t_1_H,At_bats_t_1_H,Bateos_2_t_1_H,Bateos_promedio_2_t_1_H,Bateos_promedio_t_1_H,Bateos_t_1_H,Dobles_2_t_1_H,Dobles_t_1_H,Home_runs_2_t_1_H,Home_runs_t_1_H,...,Porcentaje_on_base_2_t_1_H,Porcentaje_on_base_t_1_H,Porcentaje_slugging_2_t_1_H,Porcentaje_slugging_t_1_H,Runs_batted_in_2_t_1_H,Runs_batted_in_t_1_H,Triples_2_t_1_H,Triples_t_1_H,WAR_2_t_1_H,WAR_t_1_H
0,425104.0,652.0,29929.0,0.250000,0.500,173.0,1521.0,39.0,2025.0,45.0,...,0.250000,0.500,0.289444,0.538,10404.0,102.0,16.0,4.0,52.5625,7.25
1,425104.0,652.0,29929.0,0.250000,0.500,173.0,1521.0,39.0,2025.0,45.0,...,0.250000,0.500,0.289444,0.538,10404.0,102.0,16.0,4.0,52.5625,7.25
2,253009.0,503.0,18769.0,0.091809,0.303,137.0,900.0,30.0,484.0,22.0,...,0.154449,0.393,0.272484,0.522,4900.0,70.0,49.0,7.0,15.9201,3.99
3,412164.0,642.0,34225.0,1.000000,1.000,185.0,1849.0,43.0,900.0,30.0,...,1.000000,1.000,1.000000,1.000,8649.0,93.0,81.0,9.0,10.3041,3.21
4,412164.0,642.0,34225.0,1.000000,1.000,185.0,1849.0,43.0,900.0,30.0,...,1.000000,1.000,1.000000,1.000,8649.0,93.0,81.0,9.0,10.3041,3.21
5,404496.0,636.0,29584.0,0.118336,0.344,172.0,1444.0,38.0,1089.0,33.0,...,0.156025,0.395,0.327184,0.572,10000.0,100.0,16.0,4.0,33.0625,5.75
6,404496.0,636.0,29584.0,0.118336,0.344,172.0,1444.0,38.0,1089.0,33.0,...,0.156025,0.395,0.327184,0.572,10000.0,100.0,16.0,4.0,33.0625,5.75
7,322624.0,568.0,29241.0,0.096100,0.310,171.0,1225.0,35.0,1156.0,34.0,...,0.144400,0.380,0.281961,0.531,8464.0,92.0,16.0,4.0,12.3201,3.51
8,293764.0,542.0,27889.0,0.097969,0.313,167.0,784.0,28.0,961.0,31.0,...,0.133225,0.365,0.244036,0.494,8464.0,92.0,9.0,3.0,28.6225,5.35
9,412164.0,642.0,34225.0,1.000000,1.000,185.0,1849.0,43.0,900.0,30.0,...,1.000000,1.000,1.000000,1.000,8649.0,93.0,81.0,9.0,10.3041,3.21
10,404496.0,636.0,29584.0,0.118336,0.344,172.0,1444.0,38.0,1089.0,33.0,...,0.156025,0.395,0.327184,0.572,10000.0,100.0,16.0,4.0,33.0625,5.75
11,339889.0,583.0,26896.0,0.094249,0.307,164.0,1089.0,33.0,484.0,22.0,...,0.157609,0.397,0.354025,0.595,6400.0,80.0,16.0,4.0,11.6281,3.41
12,355216.0,596.0,25281.0,0.094864,0.308,159.0,1369.0,37.0,961.0,31.0,...,0.145161,0.381,0.287296,0.536,9801.0,99.0,49.0,7.0,16.9744,4.12
13,404496.0,636.0,29584.0,0.118336,0.344,172.0,1444.0,38.0,1089.0,33.0,...,0.156025,0.395,0.327184,0.572,10000.0,100.0,16.0,4.0,33.0625,5.75
14,404496.0,636.0,29584.0,0.118336,0.344,172.0,1444.0,38.0,1089.0,33.0,...,0.156025,0.395,0.327184,0.572,10000.0,100.0,16.0,4.0,33.0625,5.75
15,378225.0,615.0,31684.0,0.250000,0.500,178.0,3364.0,58.0,1225.0,35.0,...,0.250000,0.500,0.281961,0.531,7569.0,87.0,9.0,3.0,6.7600,2.60
16,339889.0,583.0,26896.0,0.094249,0.307,164.0,1089.0,33.0,484.0,22.0,...,0.157609,0.397,0.354025,0.595,6400.0,80.0,16.0,4.0,11.6281,3.41
17,341056.0,584.0,31329.0,1.000000,1.000,177.0,1089.0,33.0,1444.0,38.0,...,1.000000,1.000,1.000000,1.000,9025.0,95.0,25.0,5.0,30.2500,5.50
18,379456.0,616.0,31329.0,0.092416,0.304,177.0,1600.0,40.0,841.0,29.0,...,0.166464,0.408,0.319225,0.565,7396.0,86.0,4.0,2.0,8.4100,2.90
19,293764.0,542.0,27889.0,0.097969,0.313,167.0,784.0,28.0,961.0,31.0,...,0.133225,0.365,0.244036,0.494,8464.0,92.0,9.0,3.0,28.6225,5.35

In [169]:
empiric_panel_hitter.fillna(0, inplace = True)
empiric_panel_pitcher.fillna(0, inplace = True)

Verifiquemos si queda alguna columna con alguna entrada tipo *NaN*:

In [170]:
# Hitter
hitter_nan = empiric_panel_hitter.isna().any()
hitter_name = empiric_panel_hitter.columns
for con in range(0, len(hitter_nan)):
    if hitter_nan[con]:
        print("Name: " + str(hitter_name[con]))

In [171]:
# Pitcher
pitcher_nan = empiric_panel_pitcher.isna().any()
pitcher_name = empiric_panel_pitcher.columns
for con in range(0, len(pitcher_nan)):
    if pitcher_nan[con]:
        print("Name: " + str(pitcher_name[con]))

Obtengamos el máximo de cada una de las medidas de desempeño, de periodos *t_1*, por equipo que han obtenido a lo largo de todas la temporadas

Para evitar problemas con el tipo de *ID*, creemos una que sea numérica para evitar usar los nombres de los jugadores

In [172]:
# Hitter
empiric_panel_hitter['id'] =  empiric_panel_hitter.groupby(['Jugador']).ngroup()
empiric_panel_hitter.reset_index(drop = True, inplace = True)
# Pitcher
empiric_panel_pitcher['id'] =  empiric_panel_pitcher.groupby(['Jugador']).ngroup()
empiric_panel_pitcher.reset_index(drop = True, inplace = True)

Obtengamos la transformación para obtener la $Y$ del modelo empírico a partir de los rezagos de las raices de dichos salarios

In [173]:
# Función de rezagos de raices
def sqrt_dif(X):
    S = []
    for i in range(0, len(X)-1):
        d = np.sqrt(X[i+1])-np.sqrt(X[i])
        S.append(d)
    try:
        S.append(d)
    except: 
        S.append(0)
    return S

In [174]:
Y_hitter = []
for p in empiric_panel_hitter["id"].unique():
    # Filtremos todos los sueldos (ln) de cada jugador por separado
    X = empiric_panel_hitter[empiric_panel_hitter["id"] == p]["ln_Sueldo_ajustado_t"].values
    # Aplicación de la función
    S = sqrt_dif(X)
    # Añadimos los datos de manera ordenada
    Y_hitter = np.concatenate((Y_hitter, S))
# Agregamos la columna:
empiric_panel_hitter["Y"] = Y_hitter

In [175]:
empiric_panel_hitter["Y"]

0      0.000000
1     -0.510464
2      0.364601
3      0.031139
4      0.031139
         ...
191    0.329486
192    0.329486
193    0.000000
194    0.070465
195    0.070465
Name: Y, Length: 196, dtype: float64

In [176]:
Y_pitcher = []
for p in empiric_panel_pitcher["id"].unique():
    # Filtremos todos los sueldos (ln) de cada jugador por separado
    X = empiric_panel_pitcher[empiric_panel_pitcher["id"] == p]["ln_Sueldo_ajustado_t"].values
    # Aplicación de la función
    S = sqrt_dif(X)
    # Añadimos los datos de manera ordenada
    Y_pitcher = np.concatenate((Y_pitcher, S))
# Agregamos la columna:
empiric_panel_pitcher["Y"] = Y_pitcher

In [177]:
empiric_panel_pitcher["Y"]

0      0.158037
1      0.124477
2      0.124477
3     -0.281860
4      0.233682
         ...
214    0.219029
215    0.000000
216    0.070465
217   -0.117079
218   -0.117079
Name: Y, Length: 219, dtype: float64

Contruyamos las dummy *I* del modelo empírico

In [178]:
# Long of the stats
end_hitter_name = int((len(hitter_high_stat) + len(hitter_low_stat))/2)

In [179]:
hitter_regular_stats

['At_bats_2_t_1',
 'At_bats_t_1',
 'Bateos_2_t_1',
 'Bateos_promedio_2_t_1',
 'Bateos_promedio_t_1',
 'Bateos_t_1',
 'Dobles_2_t_1',
 'Dobles_t_1',
 'Home_runs_2_t_1',
 'Home_runs_t_1',
 'Juegos_iniciados_2_t_1',
 'Juegos_iniciados_t_1',
 'Porcentaje_On_base_plus_slugging_2_t_1',
 'Porcentaje_On_base_plus_slugging_t_1',
 'Porcentaje_on_base_2_t_1',
 'Porcentaje_on_base_t_1',
 'Porcentaje_slugging_2_t_1',
 'Porcentaje_slugging_t_1',
 'Runs_batted_in_2_t_1',
 'Runs_batted_in_t_1',
 'Triples_2_t_1',
 'Triples_t_1',
 'WAR_2_t_1',
 'WAR_t_1']

In [180]:
# Hitter
for sport_stat in range(0,end_hitter_name):
    I_hitter = []
    for y,max_stat,min_stat in zip(empiric_panel_hitter[hitter_regular_stats[sport_stat]],
                                   empiric_panel_hitter[hitter_high_stat[sport_stat]],
                                   empiric_panel_hitter[hitter_low_stat[sport_stat]]):
        # Dummy condition
        if y > (max_stat + min_stat)/2:
            I_hitter.append(0)
        else: 
            I_hitter.append(1)
    
    I_name = hitter_regular_stats[sport_stat] + '_I'
    empiric_panel_hitter[I_name] = I_hitter

Veamos los resultados

In [181]:
"""hitter_names = empiric_panel_hitter.columns
for index in range(0,len(hitter_names)):
    print("Name: " + str(hitter_names[index]))
    print("index: " + str(index))"""

'hitter_names = empiric_panel_hitter.columns\nfor index in range(0,len(hitter_names)):\n    print("Name: " + str(hitter_names[index]))\n    print("index: " + str(index))'

In [182]:
# Hitter
hitter_nan = empiric_panel_hitter.isna().any()
hitter_name = empiric_panel_hitter.columns
for con in range(0, len(hitter_nan)):
    if hitter_nan[con]:
        print("Name: " + str(hitter_name[con]))

In [183]:
start = empiric_panel_hitter.columns.get_loc('At_bats_2_t_1_I')
end = empiric_panel_hitter.columns.get_loc('WAR_t_1_I') + 1
empiric_panel_hitter.iloc[:,start:end]

,At_bats_2_t_1_I,At_bats_t_1_I,Bateos_2_t_1_I,Bateos_promedio_2_t_1_I,Bateos_promedio_t_1_I,Bateos_t_1_I,Dobles_2_t_1_I,Dobles_t_1_I,Home_runs_2_t_1_I,Home_runs_t_1_I,...,Porcentaje_on_base_2_t_1_I,Porcentaje_on_base_t_1_I,Porcentaje_slugging_2_t_1_I,Porcentaje_slugging_t_1_I,Runs_batted_in_2_t_1_I,Runs_batted_in_t_1_I,Triples_2_t_1_I,Triples_t_1_I,WAR_2_t_1_I,WAR_t_1_I
0,0,0,0,1,0,0,1,1,1,0,...,1,0,0,0,0,0,0,0,1,1
1,0,0,0,1,0,0,1,1,1,0,...,1,0,0,0,0,0,0,0,1,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
3,1,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
4,1,0,1,1,1,0,1,0,1,1,...,1,1,1,1,1,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
192,1,1,1,0,0,1,1,1,1,1,...,0,0,0,0,1,1,1,1,1,1
193,1,1,1,1,0,1,1,1,1,1,...,1,0,0,0,1,1,1,1,1,1
194,1,1,1,1,0,1,1,1,1,1,...,1,0,0,0,1,1,1,1,1,1
195,1,1,1,0,0,1,1,1,1,1,...,1,0,1,0,1,1,1,1,0,0

Repitamos el mismo proceso para los lanzadores

In [184]:
# Long of stats
end_pitcher_name = int((len(pitcher_high_stat) + len(pitcher_low_stat))/2)

In [185]:
# Pitcher
for sport_stat in range(0,end_pitcher_name):
    I_pitcher = []
    for y,max_stat,min_stat in zip(empiric_panel_pitcher[pitcher_regular_stats[sport_stat]],
                                   empiric_panel_pitcher[pitcher_high_stat[sport_stat]],
                                   empiric_panel_pitcher[pitcher_low_stat[sport_stat]]):
        if y > (max_stat + min_stat)/2:
            I_pitcher.append(0)
        else: 
            I_pitcher.append(1)
    
    I_name = pitcher_regular_stats[sport_stat] + '_I'
    empiric_panel_pitcher[I_name] = I_pitcher

In [186]:
"""pitcher_names = empiric_panel_pitcher.columns
for index in range(0,len(pitcher_names)):
    print("Name: " + str(pitcher_names[index]))
    print("index: " + str(index))"""

'pitcher_names = empiric_panel_pitcher.columns\nfor index in range(0,len(pitcher_names)):\n    print("Name: " + str(pitcher_names[index]))\n    print("index: " + str(index))'

In [187]:
# Pitcher
pitcher_nan = empiric_panel_pitcher.isna().any()
pitcher_name = empiric_panel_pitcher.columns
for con in range(0, len(pitcher_nan)):
    if pitcher_nan[con]:
        print("Name: " + str(pitcher_name[con]))

In [188]:
start = empiric_panel_pitcher.columns.get_loc('Bateos_2_t_1_I')
end = empiric_panel_pitcher.columns.get_loc('Wins_t_1_I') + 1
empiric_panel_pitcher.iloc[:,start:end]

,Bateos_2_t_1_I,Bateos_t_1_I,Carreras_2_t_1_I,Carreras_ganadas_2_t_1_I,Carreras_ganadas_t_1_I,Carreras_t_1_I,Comando_2_t_1_I,Comando_t_1_I,Control_2_t_1_I,Control_t_1_I,...,Strike_outs_2_t_1_I,Strike_outs_t_1_I,WAR_2_t_1_I,WAR_t_1_I,WHIP_2_t_1_I,WHIP_t_1_I,Walks_2_t_1_I,Walks_t_1_I,Wins_2_t_1_I,Wins_t_1_I
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1,0,0,...,1,1,1,1,0,0,1,1,1,1
2,1,0,1,1,1,0,1,1,1,0,...,0,0,1,1,1,0,1,0,0,0
3,0,0,0,0,0,0,1,0,1,1,...,0,0,1,1,1,1,0,0,1,0
4,1,0,0,0,0,0,1,1,1,1,...,1,0,1,1,1,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,1,1,1,1,1,1,1,1,1,1,...,1,0,1,1,1,1,1,1,1,0
215,0,0,0,0,0,0,1,1,1,1,...,0,0,1,1,1,1,0,0,0,0
216,0,0,0,0,0,0,1,1,1,1,...,0,0,1,1,1,1,0,0,0,0
217,0,0,1,1,1,1,0,0,1,1,...,0,0,0,0,1,1,1,0,0,0
218,0,0,0,0,0,0,0,0,1,1,...,1,0,1,1,1,1,1,1,0,0

Obtengamos las variables auxiliares

In [189]:
# Good practice
hitter_high_stat = sorted(hitter_high_stat)
# Dummy
I_hitter = sorted([stat + '_I' for stat in hitter_regular_stats])

Verifiquemos que tengan la misma longitud

In [190]:
len(I_hitter) == len(hitter_high_stat) == len(hitter_regular_stats)

True

In [191]:
# Pitcher
for stat in range(0,len(hitter_regular_stats)):
    # Variable auxiliar
    X_hitter = []
    
    # Variables 
    i = (-1)**(empiric_panel_hitter[I_hitter[stat]])
    x = empiric_panel_hitter[hitter_regular_stats[stat]]/np.sqrt(empiric_panel_hitter[hitter_high_stat[stat]])
    X_hitter = i*x
    
    # X name
    name = 'X_' + hitter_regular_stats[stat]
    empiric_panel_hitter[name] = X_hitter

In [192]:
# Pitcher
hitter_nan = empiric_panel_hitter.isna().any()
hitter_name = empiric_panel_hitter.columns
for con in range(0, len(hitter_nan)):
    if hitter_nan[con]:
        print("Name: " + str(hitter_name[con]))

In [193]:
# define a list of suffixes to drop
drop_suffix = ['_I', '_L', '_H']

# Use a list comprehension to filter the columns to drop
hitter_cols_to_drop = [col for col in empiric_panel_hitter.columns if col.endswith(tuple(drop_suffix))]

# Drop the selected columns
empiric_panel_hitter = empiric_panel_hitter.drop(hitter_cols_to_drop,
                                                 axis=1)

In [194]:
empiric_panel_hitter.shape

(196, 165)

In [195]:
empiric_panel_hitter['Posicion_t'].value_counts()

SP    37
C     32
RF    27
2B    22
1B    17
LF    16
DH    14
RP    13
3B     7
SS     6
CF     5
Name: Posicion_t, dtype: int64

Veamos todas las variables del panel

In [196]:
panel_columns = empiric_panel_hitter.columns

for name in panel_columns:
    print(name)

Acronimo_t
Acronimo_t_1
Altura_t
Altura_t_1
Anio_de_agente_libre_t
Anio_de_agente_libre_t_1
Anio_t
Anios_de_contrato_t
Anios_de_contrato_t_1
Antiguedad_t
Antiguedad_t_1
At-bats_2_t
At-bats_t
At_bats_2_t
At_bats_2_t_1
At_bats_t
At_bats_t_1
Bateos_2_t
Bateos_2_t_1
Bateos_promedio_2_t
Bateos_promedio_2_t_1
Bateos_promedio_t
Bateos_promedio_t_1
Bateos_t
Bateos_t_1
Bono_por_firma_t
Bono_por_firma_t_1
Cantidad de equipos_t
Cantidad_agentes_libres_t
Cantidad_agentes_libres_t_1
Cantidad_de_equipos_t
Cantidad_de_equipos_t_1
Dobles_2_t
Dobles_2_t_1
Dobles_t
Dobles_t_1
Edad_al_firmar_t
Edad_al_firmar_t_1
Edad_t
Equipo_anterior
Equipo_t
Equipo_t_1
Estado_t
Ganancias_t
Ganancias_t_1
Home-runs_2_t
Home-runs_t
Home_runs_2_t
Home_runs_2_t_1
Home_runs_t
Home_runs_t_1
Juegos totales_t
Juegos_iniciados_2_t
Juegos_iniciados_2_t_1
Juegos_iniciados_t
Juegos_iniciados_t_1
Juegos_t
Juegos_t_1
Juegos_totales_t
Juegos_totales_t_1
Jugador
Pago_efectivo_t
Pago_efectivo_t_1
Pennants won_t
Pennants_won_t
Pennants_won_t_1
Peso_t
Peso_t_1
Playoffs_t
Playoffs_t_1
Porcentaje_On-base-plus-slugging_2_t
Porcentaje_On-base-plus-slugging_t
Porcentaje_On_base_plus_slugging_2_t
Porcentaje_On_base_plus_slugging_2_t_1
Porcentaje_On_base_plus_slugging_t
Porcentaje_On_base_plus_slugging_t_1
Porcentaje_juegos_iniciados_2_t
Porcentaje_juegos_iniciados_2_t_1
Porcentaje_juegos_iniciados_t
Porcentaje_juegos_iniciados_t_1
Porcentaje_juegos_t
Porcentaje_juegos_t_1
Porcentaje_on-base_2_t
Porcentaje_on-base_t
Porcentaje_on_base_2_t
Porcentaje_on_base_2_t_1
Porcentaje_on_base_t
Porcentaje_on_base_t_1
Porcentaje_slugging_2_t
Porcentaje_slugging_2_t_1
Porcentaje_slugging_t
Porcentaje_slugging_t_1
Posicion_t
Posicion_t_1
Promedio_victorias_t
Promedio_victorias_t_1
Runs-batted-in_2_t
Runs-batted-in_t
Runs_batted_in_2_t
Runs_batted_in_2_t_1
Runs_batted_in_t
Runs_batted_in_t_1
Status_agente_libre
Sueldo_ajustado_t
Sueldo_ajustado_t_1
Sueldo_base_t
Sueldo_base_t_1
Sueldo_porcentual_t
Sueldo_porcentual_t_1
Sueldo_regular_t
Sueldo_regular_t_1
TVS_2_t
TVS_2_t_1
TVS_t
TVS_t_1
Triples_2_t
Triples_2_t_1
Triples_t
Triples_t_1
Valor_contrato
Valor_contrato_promedio_t
Valor_contrato_promedio_t_1
Valor_contrato_total_t
Valor_contrato_total_t_1
Valor_del_contrato_t
Valor_del_contrato_t_1
Valor_promedio_contrato
Victorias_t
Victorias_t_1
WAR_2_t
WAR_2_t_1
WAR_t
WAR_t_1
WS ganadas_t
WS_ganadas_t
WS_ganadas_t_1
ln_Sueldo_ajustado_t
ln_Sueldo_base_t
ln_Sueldo_regular_t
id
Y
X_At_bats_2_t_1
X_At_bats_t_1
X_Bateos_2_t_1
X_Bateos_promedio_2_t_1
X_Bateos_promedio_t_1
X_Bateos_t_1
X_Dobles_2_t_1
X_Dobles_t_1
X_Home_runs_2_t_1
X_Home_runs_t_1
X_Juegos_iniciados_2_t_1
X_Juegos_iniciados_t_1
X_Porcentaje_On_base_plus_slugging_2_t_1
X_Porcentaje_On_base_plus_slugging_t_1
X_Porcentaje_on_base_2_t_1
X_Porcentaje_on_base_t_1
X_Porcentaje_slugging_2_t_1
X_Porcentaje_slugging_t_1
X_Runs_batted_in_2_t_1
X_Runs_batted_in_t_1
X_Triples_2_t_1
X_Triples_t_1
X_WAR_2_t_1
X_WAR_t_1

In [197]:
general_dynamic_path = 'ETL_Data/Panel/Yearly_average/Dynamic_model/'

In [198]:
empiric_panel_hitter.to_csv(general_dynamic_path + 'panel_hitters_ya_t_1' + '.csv',
                            index = False)

Ahora, filtremos las columnas que contienen las medidas de desempeño de los periodos **t_1**. Para ello, encontremos primero los índices de dichas variables

In [199]:
# Pitcher
for stat in range(0,len(hitter_regular_stats)):
    # Stat
    print(colored(hitter_regular_stats[stat], "cyan"))
    
    # X name
    name = 'X_' + hitter_regular_stats[stat]
    
    # OLS variables
    Y = empiric_panel_hitter['Y'].tolist()
    X = empiric_panel_hitter[name].tolist()
    X = sm.add_constant(X)
    
    # Modelo
    model = sm.OLS(Y, X,
                   missing = 'drop').fit()
    print(model.summary())
    print("\n")

At_bats_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                 -0.003
Method:                 Least Squares   F-statistic:                    0.4694
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.494
Time:                        12:41:51   Log-Likelihood:                 65.721
No. Observations:                 196   AIC:                            -127.4
Df Residuals:                     194   BIC:                            -120.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0012      0.013      0.096      0.924      -0.024       0.026
x1          3.599e-05   5.25e-05      0.685      0.494   -6.76e-05       0.000
==============================================================================
Omnibus:                       17.580   Durbin-Watson:                   1.750
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               56.051
Skew:                          -0.182   Prob(JB):                     6.74e-13
Kurtosis:                       5.594   Cond. No.                         243.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


At_bats_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.005
Method:                 Least Squares   F-statistic:                   0.05291
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.818
Time:                        12:41:51   Log-Likelihood:                 65.511
No. Observations:                 196   AIC:                            -127.0
Df Residuals:                     194   BIC:                            -120.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0014      0.013      0.108      0.914      -0.025       0.028
x1             0.0002      0.001      0.230      0.818      -0.002       0.002
==============================================================================
Omnibus:                       17.087   Durbin-Watson:                   1.743
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               54.267
Skew:                          -0.159   Prob(JB):                     1.64e-12
Kurtosis:                       5.558   Cond. No.                         13.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Bateos_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                    0.1276
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.721
Time:                        12:41:51   Log-Likelihood:                 65.549
No. Observations:                 196   AIC:                            -127.1
Df Residuals:                     194   BIC:                            -120.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0023      0.012      0.184      0.854      -0.022       0.027
x1          7.342e-05      0.000      0.357      0.721      -0.000       0.000
==============================================================================
Omnibus:                       17.373   Durbin-Watson:                   1.748
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               55.278
Skew:                          -0.173   Prob(JB):                     9.92e-13
Kurtosis:                       5.579   Cond. No.                         60.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Bateos_promedio_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.005
Method:                 Least Squares   F-statistic:                 0.0002000
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.989
Time:                        12:41:51   Log-Likelihood:                 65.484
No. Observations:                 196   AIC:                            -127.0
Df Residuals:                     194   BIC:                            -120.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0026      0.013      0.204      0.838      -0.023       0.028
x1            -0.0010      0.067     -0.014      0.989      -0.134       0.132
==============================================================================
Omnibus:                       17.051   Durbin-Watson:                   1.743
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               54.468
Skew:                          -0.152   Prob(JB):                     1.49e-12
Kurtosis:                       5.565   Cond. No.                         5.43
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Bateos_promedio_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.005
Method:                 Least Squares   F-statistic:                   0.03434
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.853
Time:                        12:41:51   Log-Likelihood:                 65.502
No. Observations:                 196   AIC:                            -127.0
Df Residuals:                     194   BIC:                            -120.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0010      0.015      0.069      0.945      -0.029       0.031
x1             0.0071      0.038      0.185      0.853      -0.068       0.083
==============================================================================
Omnibus:                       17.083   Durbin-Watson:                   1.743
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               54.653
Skew:                          -0.153   Prob(JB):                     1.36e-12
Kurtosis:                       5.569   Cond. No.                         3.24
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Bateos_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.005
Method:                 Least Squares   F-statistic:                    0.1037
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.748
Time:                        12:41:51   Log-Likelihood:                 65.537
No. Observations:                 196   AIC:                            -127.1
Df Residuals:                     194   BIC:                            -120.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0015      0.013      0.113      0.910      -0.024       0.027
x1             0.0007      0.002      0.322      0.748      -0.003       0.005
==============================================================================
Omnibus:                       17.184   Durbin-Watson:                   1.743
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               54.858
Skew:                          -0.160   Prob(JB):                     1.22e-12
Kurtosis:                       5.572   Cond. No.                         6.50
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Dobles_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.005
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     1.045
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.308
Time:                        12:41:51   Log-Likelihood:                 66.011
No. Observations:                 196   AIC:                            -128.0
Df Residuals:                     194   BIC:                            -121.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0012      0.012      0.094      0.925      -0.023       0.026
x1             0.0011      0.001      1.022      0.308      -0.001       0.003
==============================================================================
Omnibus:                       17.526   Durbin-Watson:                   1.759
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               54.569
Skew:                          -0.197   Prob(JB):                     1.41e-12
Kurtosis:                       5.555   Cond. No.                         12.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Dobles_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.015
Model:                            OLS   Adj. R-squared:                  0.010
Method:                 Least Squares   F-statistic:                     3.053
Date:                Mon, 20 Mar 2023   Prob (F-statistic):             0.0822
Time:                        12:41:51   Log-Likelihood:                 67.014
No. Observations:                 196   AIC:                            -130.0
Df Residuals:                     194   BIC:                            -123.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0041      0.013     -0.314      0.754      -0.030       0.021
x1             0.0081      0.005      1.747      0.082      -0.001       0.017
==============================================================================
Omnibus:                       16.681   Durbin-Watson:                   1.756
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               50.731
Skew:                          -0.174   Prob(JB):                     9.64e-12
Kurtosis:                       5.468   Cond. No.                         2.95
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Home_runs_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.005
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     1.043
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.308
Time:                        12:41:51   Log-Likelihood:                 66.010
No. Observations:                 196   AIC:                            -128.0
Df Residuals:                     194   BIC:                            -121.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0022      0.012      0.178      0.859      -0.022       0.027
x1             0.0012      0.001      1.022      0.308      -0.001       0.004
==============================================================================
Omnibus:                       16.703   Durbin-Watson:                   1.743
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               54.190
Skew:                          -0.113   Prob(JB):                     1.71e-12
Kurtosis:                       5.566   Cond. No.                         10.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Home_runs_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.014
Model:                            OLS   Adj. R-squared:                  0.009
Method:                 Least Squares   F-statistic:                     2.794
Date:                Mon, 20 Mar 2023   Prob (F-statistic):             0.0962
Time:                        12:41:51   Log-Likelihood:                 66.886
No. Observations:                 196   AIC:                            -129.8
Df Residuals:                     194   BIC:                            -123.2
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0007      0.013     -0.052      0.958      -0.025       0.024
x1             0.0088      0.005      1.672      0.096      -0.002       0.019
==============================================================================
Omnibus:                       17.221   Durbin-Watson:                   1.741
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               54.474
Skew:                          -0.170   Prob(JB):                     1.48e-12
Kurtosis:                       5.560   Cond. No.                         2.42
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Juegos_iniciados_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                    0.2313
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.631
Time:                        12:41:51   Log-Likelihood:                 65.601
No. Observations:                 196   AIC:                            -127.2
Df Residuals:                     194   BIC:                            -120.6
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0017      0.013      0.132      0.895      -0.023       0.026
x1          9.703e-05      0.000      0.481      0.631      -0.000       0.000
==============================================================================
Omnibus:                       17.417   Durbin-Watson:                   1.747
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               55.510
Skew:                          -0.174   Prob(JB):                     8.83e-13
Kurtosis:                       5.584   Cond. No.                         63.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Juegos_iniciados_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                    0.1290
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.720
Time:                        12:41:51   Log-Likelihood:                 65.549
No. Observations:                 196   AIC:                            -127.1
Df Residuals:                     194   BIC:                            -120.5
Df Model:                           1
Covariance Type:            nonrobust

Repitamos el mismo procedimiento para los filderos

In [200]:
# Good practice
pitcher_high_stat = sorted(pitcher_high_stat)
# Dummy
I_pitcher = sorted([stat + '_I' for stat in pitcher_regular_stats])

Verifiquemos que tengan la misma longitud

In [201]:
len(I_pitcher) == len(pitcher_high_stat) == len(pitcher_regular_stats)

True

In [202]:
# Pitcher
for stat in range(0,len(pitcher_regular_stats)):
    # Variable auxiliar
    X_pitcher = []
    
    # Variables 
    i = (-1)**(empiric_panel_pitcher[I_pitcher[stat]])
    x = empiric_panel_pitcher[pitcher_regular_stats[stat]]/np.sqrt(empiric_panel_pitcher[pitcher_high_stat[stat]])
    X_pitcher = i*x
    
    # X name
    name = 'X_' + pitcher_regular_stats[stat]
    empiric_panel_pitcher[name] = X_pitcher

In [203]:
# Pitcher
pitcher_nan = empiric_panel_pitcher.isna().any()
pitcher_name = empiric_panel_pitcher.columns
for con in range(0, len(pitcher_nan)):
    if pitcher_nan[con]:
        print("Name: " + str(pitcher_name[con]))

Tenemos que borrar las columnas que terminan con '_L', '_H' o '_I'

In [204]:
# define a list of suffixes to drop
drop_suffix = ['_I', '_L', '_H']

# Use a list comprehension to filter the columns to drop
fielder_cols_to_drop = [col for col in empiric_panel_pitcher.columns if col.endswith(tuple(drop_suffix))]

# Drop the selected columns
empiric_panel_pitcher = empiric_panel_pitcher.drop(fielder_cols_to_drop,
                                                   axis=1)

In [205]:
empiric_panel_pitcher.shape

(219, 173)

In [206]:
empiric_panel_pitcher['Posicion_t'].value_counts()

RP       116
SP        76
SS        12
RP/CL     12
RF         3
Name: Posicion_t, dtype: int64

In [207]:
panel_columns = empiric_panel_pitcher.columns

for name in panel_columns:
    print(name)

Acronimo_t
Acronimo_t_1
Altura_t
Altura_t_1
Anio_de_agente_libre_t
Anio_de_agente_libre_t_1
Anio_t
Anios_de_contrato_t
Anios_de_contrato_t_1
Antiguedad_t
Antiguedad_t_1
Bateos_2_t
Bateos_2_t_1
Bateos_t
Bateos_t_1
Bono_por_firma_t
Bono_por_firma_t_1
Cantidad de equipos_t
Cantidad_agentes_libres_t
Cantidad_agentes_libres_t_1
Cantidad_de_equipos_t
Cantidad_de_equipos_t_1
Carreras_2_t
Carreras_2_t_1
Carreras_ganadas_2_t
Carreras_ganadas_2_t_1
Carreras_ganadas_t
Carreras_ganadas_t_1
Carreras_t
Carreras_t_1
Comando_2_t
Comando_2_t_1
Comando_t
Comando_t_1
Control_2_t
Control_2_t_1
Control_t
Control_t_1
Dominio_2_t
Dominio_2_t_1
Dominio_t
Dominio_t_1
ERA_2_t
ERA_2_t_1
ERA_t
ERA_t_1
Edad_al_firmar_t
Edad_al_firmar_t_1
Edad_t
Equipo_anterior
Equipo_t
Equipo_t_1
Estado_t
Ganancias_t
Ganancias_t_1
Inning_pitched_2_t
Inning_pitched_2_t_1
Inning_pitched_t
Inning_pitched_t_1
Juegos totales_t
Juegos_iniciados_t
Juegos_iniciados_t_1
Juegos_t
Juegos_t_1
Juegos_totales_t
Juegos_totales_t_1
Jugador
Losses_2_t
Losses_2_t_1
Losses_t
Losses_t_1
Pago_efectivo_t
Pago_efectivo_t_1
Pennants won_t
Pennants_won_t
Pennants_won_t_1
Peso_t
Peso_t_1
Playoffs_t
Playoffs_t_1
Porcentaje_juegos_t
Porcentaje_juegos_t_1
Posicion_t
Posicion_t_1
Promedio_victorias_t
Promedio_victorias_t_1
Saves_2_t
Saves_2_t_1
Saves_t
Saves_t_1
Status_agente_libre
Strike-outs_2_t
Strike-outs_t
Strike_outs_2_t
Strike_outs_2_t_1
Strike_outs_t
Strike_outs_t_1
Sueldo_ajustado_t
Sueldo_ajustado_t_1
Sueldo_base_t
Sueldo_base_t_1
Sueldo_porcentual_t
Sueldo_porcentual_t_1
Sueldo_regular_t
Sueldo_regular_t_1
TVS_2_t
TVS_2_t_1
TVS_t
TVS_t_1
Valor_contrato
Valor_contrato_promedio_t
Valor_contrato_promedio_t_1
Valor_contrato_total_t
Valor_contrato_total_t_1
Valor_del_contrato_t
Valor_del_contrato_t_1
Valor_promedio_contrato
Victorias_t
Victorias_t_1
WAR_2_t
WAR_2_t_1
WAR_t
WAR_t_1
WHIP_2_t
WHIP_2_t_1
WHIP_t
WHIP_t_1
WS ganadas_t
WS_ganadas_t
WS_ganadas_t_1
Walks_2_t
Walks_2_t_1
Walks_t
Walks_t_1
Wins_2_t
Wins_2_t_1
Wins_t
Wins_t_1
ln_Sueldo_ajustado_t
ln_Sueldo_base_t
ln_Sueldo_regular_t
id
Y
X_Bateos_2_t_1
X_Bateos_t_1
X_Carreras_2_t_1
X_Carreras_ganadas_2_t_1
X_Carreras_ganadas_t_1
X_Carreras_t_1
X_Comando_2_t_1
X_Comando_t_1
X_Control_2_t_1
X_Control_t_1
X_Dominio_2_t_1
X_Dominio_t_1
X_ERA_2_t_1
X_ERA_t_1
X_Inning_pitched_2_t_1
X_Inning_pitched_t_1
X_Losses_2_t_1
X_Losses_t_1
X_Saves_2_t_1
X_Saves_t_1
X_Strike_outs_2_t_1
X_Strike_outs_t_1
X_WAR_2_t_1
X_WAR_t_1
X_WHIP_2_t_1
X_WHIP_t_1
X_Walks_2_t_1
X_Walks_t_1
X_Wins_2_t_1
X_Wins_t_1

In [208]:
empiric_panel_pitcher.to_csv(general_dynamic_path + 'panel_fielders_ya_t_1' + '.csv',
                             index = False)

In [209]:
# Pitcher
for stat in range(0,len(pitcher_regular_stats)):
    # Stat
    print(colored(pitcher_regular_stats[stat], "cyan"))
    
    # X name
    name = 'X_' + pitcher_regular_stats[stat]
    
    # OLS variables
    Y = empiric_panel_pitcher['Y'].tolist()
    X = empiric_panel_pitcher[name].tolist()
    X = sm.add_constant(X)
    
    # Modelo
    model = sm.OLS(Y, X,
                   missing = 'drop').fit()
    print(model.summary())
    print("\n")

Bateos_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.008
Model:                            OLS   Adj. R-squared:                  0.003
Method:                 Least Squares   F-statistic:                     1.653
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.200
Time:                        12:41:52   Log-Likelihood:                 74.978
No. Observations:                 219   AIC:                            -146.0
Df Residuals:                     217   BIC:                            -139.2
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0321      0.012      2.727      0.007       0.009       0.055
x1            -0.0002      0.000     -1.286      0.200      -0.000       0.000
==============================================================================
Omnibus:                        8.007   Durbin-Watson:                   1.862
Prob(Omnibus):                  0.018   Jarque-Bera (JB):               13.584
Skew:                           0.119   Prob(JB):                      0.00112
Kurtosis:                       4.197   Cond. No.                         77.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Bateos_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.005
Method:                 Least Squares   F-statistic:                  0.001982
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.965
Time:                        12:41:52   Log-Likelihood:                 74.148
No. Observations:                 219   AIC:                            -144.3
Df Residuals:                     217   BIC:                            -137.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0302      0.012      2.526      0.012       0.007       0.054
x1         -7.608e-05      0.002     -0.045      0.965      -0.003       0.003
==============================================================================
Omnibus:                        8.987   Durbin-Watson:                   1.835
Prob(Omnibus):                  0.011   Jarque-Bera (JB):               15.913
Skew:                           0.146   Prob(JB):                     0.000350
Kurtosis:                       4.288   Cond. No.                         7.17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Carreras_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                   0.08802
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.767
Time:                        12:41:52   Log-Likelihood:                 74.192
No. Observations:                 219   AIC:                            -144.4
Df Residuals:                     217   BIC:                            -137.6
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0295      0.012      2.487      0.014       0.006       0.053
x1          9.116e-05      0.000      0.297      0.767      -0.001       0.001
==============================================================================
Omnibus:                        9.161   Durbin-Watson:                   1.827
Prob(Omnibus):                  0.010   Jarque-Bera (JB):               16.465
Skew:                           0.145   Prob(JB):                     0.000266
Kurtosis:                       4.312   Cond. No.                         39.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Carreras_ganadas_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                    0.2390
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.625
Time:                        12:41:52   Log-Likelihood:                 74.268
No. Observations:                 219   AIC:                            -144.5
Df Residuals:                     217   BIC:                            -137.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0291      0.012      2.448      0.015       0.006       0.053
x1             0.0002      0.000      0.489      0.625      -0.000       0.001
==============================================================================
Omnibus:                        9.289   Durbin-Watson:                   1.820
Prob(Omnibus):                  0.010   Jarque-Bera (JB):               16.905
Skew:                           0.143   Prob(JB):                     0.000213
Kurtosis:                       4.331   Cond. No.                         37.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Carreras_ganadas_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                   0.02894
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.865
Time:                        12:41:52   Log-Likelihood:                 74.162
No. Observations:                 219   AIC:                            -144.3
Df Residuals:                     217   BIC:                            -137.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0297      0.012      2.487      0.014       0.006       0.053
x1             0.0004      0.003      0.170      0.865      -0.005       0.005
==============================================================================
Omnibus:                        9.146   Durbin-Watson:                   1.830
Prob(Omnibus):                  0.010   Jarque-Bera (JB):               16.220
Skew:                           0.153   Prob(JB):                     0.000301
Kurtosis:                       4.298   Cond. No.                         4.87
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Carreras_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                    0.1709
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.680
Time:                        12:41:52   Log-Likelihood:                 74.234
No. Observations:                 219   AIC:                            -144.5
Df Residuals:                     217   BIC:                            -137.7
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0291      0.012      2.425      0.016       0.005       0.053
x1             0.0010      0.002      0.413      0.680      -0.004       0.006
==============================================================================
Omnibus:                        9.355   Durbin-Watson:                   1.823
Prob(Omnibus):                  0.009   Jarque-Bera (JB):               16.657
Skew:                           0.161   Prob(JB):                     0.000242
Kurtosis:                       4.312   Cond. No.                         5.04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Comando_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.8819
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.349
Time:                        12:41:52   Log-Likelihood:                 74.592
No. Observations:                 219   AIC:                            -145.2
Df Residuals:                     217   BIC:                            -138.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0303      0.012      2.592      0.010       0.007       0.053
x1             0.0040      0.004      0.939      0.349      -0.004       0.012
==============================================================================
Omnibus:                        8.222   Durbin-Watson:                   1.837
Prob(Omnibus):                  0.016   Jarque-Bera (JB):               13.620
Skew:                           0.149   Prob(JB):                      0.00110
Kurtosis:                       4.185   Cond. No.                         2.76
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Comando_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.004
Method:                 Least Squares   F-statistic:                   0.02402
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.877
Time:                        12:41:52   Log-Likelihood:                 74.160
No. Observations:                 219   AIC:                            -144.3
Df Residuals:                     217   BIC:                            -137.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0303      0.012      2.578      0.011       0.007       0.053
x1             0.0013      0.009      0.155      0.877      -0.016       0.018
==============================================================================
Omnibus:                        8.801   Durbin-Watson:                   1.835
Prob(Omnibus):                  0.012   Jarque-Bera (JB):               15.337
Skew:                           0.147   Prob(JB):                     0.000467
Kurtosis:                       4.263   Cond. No.                         1.39
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Control_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.020
Model:                            OLS   Adj. R-squared:                  0.016
Method:                 Least Squares   F-statistic:                     4.531
Date:                Mon, 20 Mar 2023   Prob (F-statistic):             0.0344
Time:                        12:41:52   Log-Likelihood:                 76.410
No. Observations:                 219   AIC:                            -148.8
Df Residuals:                     217   BIC:                            -142.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0333      0.012      2.850      0.005       0.010       0.056
x1             0.0967      0.045      2.129      0.034       0.007       0.186
==============================================================================
Omnibus:                        8.177   Durbin-Watson:                   1.837
Prob(Omnibus):                  0.017   Jarque-Bera (JB):               14.268
Skew:                           0.107   Prob(JB):                     0.000798
Kurtosis:                       4.232   Cond. No.                         3.92
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Control_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                    0.5022
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.479
Time:                        12:41:52   Log-Likelihood:                 74.401
No. Observations:                 219   AIC:                            -144.8
Df Residuals:                     217   BIC:                            -138.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0313      0.012      2.649      0.009       0.008       0.055
x1             0.0189      0.027      0.709      0.479      -0.034       0.072
==============================================================================
Omnibus:                        8.545   Durbin-Watson:                   1.836
Prob(Omnibus):                  0.014   Jarque-Bera (JB):               15.033
Skew:                           0.125   Prob(JB):                     0.000544
Kurtosis:                       4.259   Cond. No.                         2.30
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Dominio_2_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.015
Model:                            OLS   Adj. R-squared:                  0.010
Method:                 Least Squares   F-statistic:                     3.240
Date:                Mon, 20 Mar 2023   Prob (F-statistic):             0.0733
Time:                        12:41:52   Log-Likelihood:                 75.770
No. Observations:                 219   AIC:                            -147.5
Df Residuals:                     217   BIC:                            -140.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0334      0.012      2.839      0.005       0.010       0.057
x1             0.0302      0.017      1.800      0.073      -0.003       0.063
==============================================================================
Omnibus:                        8.735   Durbin-Watson:                   1.826
Prob(Omnibus):                  0.013   Jarque-Bera (JB):               14.878
Skew:                           0.158   Prob(JB):                     0.000588
Kurtosis:                       4.237   Cond. No.                         1.48
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


Dominio_t_1
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.009
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     1.939
Date:                Mon, 20 Mar 2023   Prob (F-statistic):              0.165
Time:                        12:41:52   Log-Likelihood:                 75.122
No. Observations:                 219   AIC:                            -146.2
Df Residuals:                     217   BIC:                            -139.5
Df Model:                           1
Covariance Type:            nonrobust

In [212]:
# Dimentions
print(empiric_panel_hitter.shape)

(196, 165)

In [213]:
# Dimentions
print(empiric_panel_pitcher.shape)

(219, 173)